### ISSUE TITLE
Provide a method to use a strategy once

### ISSUE THREAD

**Issue by blueyed** [janko-m/vim-test#100]
I want to make use of vim-dispatch's focus method (which sets the action for
`:Dispatch` without arguments).

My current approach is to set and re-set `g:test#strategy`, but that feels
clumsy:

```vim
let test#python#runner = 'pytest'
let test#strategy = "dispatch"
let test#python#pytest#options = "--tb=auto -q"

" Run nearest test and focus it for Dispatch (F9).
fun! s:MyFocusTestStrategy(cmd)
  execute 'FocusDispatch '.a:cmd
  execute 'Dispatch '.a:cmd
endfun
let g:test#custom_strategies = {'focus_dispatch': function('s:MyFocusTestStrategy')}
fun! s:MyTestAndFocus()
  let l:saved = g:test#strategy
  let g:test#strategy = 'focus_dispatch'
  TestNearest
  let g:test#strategy = l:saved
endfun
nnoremap <Leader>rrt :call <SID>MyTestAndFocus()<cr>
```

For the mapping, something like `:TestNearest -strategy focus_dispatch` would
be helpful.

I don't think it needs to be added to the command(s), but could be a function, of course, e.g. `test#run_with_strategy('nearest', split(<q-args>))`.

**Comment by janko-m** [comment]
I agree this would generally be a useful feature, I think the best way is to be able to pass `-strategy=focus_dispatch` (this is how vim-dispatch has its `-compiler=...` and `-dir=...` options). I will implement this shortly.
