### ISSUE TITLE
Test status in status bar/gutter

### ISSUE THREAD

**Issue by RomainEndelin** [janko-m/vim-test#104]
First, thanks for the great plugin, it really "Does the right thing" :smile:.

I see Neoterm has a feature to show whether a test passes, straight from the status bar:

![Neoterm](https://cloud.githubusercontent.com/assets/120483/8212291/425189d2-14f1-11e5-8059-822eda0b702c.gif)

In the same idea, we could imagine to see the status of tests in the quickfix panel, or/and in the gutter.

These would add a lot to the testing workflow. I'm not sure whether it would be realistic to implement though : as far as I can see, vim-test doesn't implement a mechanism to check whether a test passes or not.

**Comment by janko-m** [comment]
If you want this mechanism in test.vim, you can simply *use* the `neoterm` strategy, or [use vim-makegreen as a custom strategy](https://github.com/janko-m/vim-test/issues/14#issuecomment-160794118). Both of these plugins have a mechanism notifying whether the shell command succeeded or not, and I think you should be able to display this status in a quickfix panel and/or in the gutter.

Implementing this mechanism is out of scope for this plugin. Test.vim's only job is to compose a test command and send it to a strategy, and then it's the responsibility of the *strategy* to provide some hooks which indicate the status of the command.

**Comment by nomasprime** [comment]
@janko do know if anyone figured this out?

**Comment by janko** [comment]
Have you tried using the Neoterm strategy, and configuring it to display test status?

**Comment by nomasprime** [comment]
@janko thanks, got this pretty much figured out with Neomake, which is preferable.

Last piece of the puzzle is eliminating escape characters and multiple whitespaces from output, see https://github.com/neomake/neomake/issues/2459.

**Comment by MarcelRobitaille** [comment]
@nomasprime where you able to get the results in the gutter or just in the quickfix list? I tried dispatch and noemake and neither is showing anything in the gutter. I would really love to quickly see which line is failing in the gutter or inline with virtual text similar to lsp.

**Comment by nomasprime** [comment]
Hi @MarcelRobitaille, was generally working but fiddly to setup and extra dependencies made it too brittle for my liking (eg, [this](https://github.com/tpope/vim-dispatch/issues/291) issue).

Also, while quickfix was quite nice, I found adding to the gutter was just too noisy combined with other diagnostics.

These days I use coc-diagnostic and vim-test with VTR. Scanning and jumping with standard vim keys is just as fast but avoiding these issues combined with finding it easier to resolve failing tests with the full output frequently anyway make this setup more efficient overall.

Hope that helps.
