### ISSUE TITLE
Possible issue for some runners when TestNearest is using regex polyfill

### ISSUE THREAD

**Issue by aaalsaleh** [janko-m/vim-test#110]
Some runners only allow running a single test (or subgroup of tests) by specifying a regex pattern matching its description instead of a specific line or class/method. For example, in Intern and Mocha, the only way to run a single test is to pass a grep with a regex of one or more suite (describe/context) and a test (it). There is no issue with vim-test finding the correct name of the suite(s) and test. However, there is an issue with the generated regex for grep'ing these tests when attempting a `TestNearest`. Currently, the generated regex in some of these framework is never prefixed with `^` or postfixed with `$` depending on the case. Take this test sample as an example:
```javascript
it('play and stop', function() {
  ...
});

it('play', function() {
 ... // cursor here
});

describe('playing', function() {
 ...
});
```
Suppose the cursor is within the test "play". If we run `TestNearest`, and the current runner generates regex to specify the test, then it would be "play". Since it is a regex pattern, it would not only match and run the test "**play**", but also the test "**play** and stop" and even the whole suite "**play**ing" and any of its subtests. Obviously, this is not the wished behaviour of `TestNearest` regex polyfill.

To solve this, `^` and `$` must be used carefully. If the cursor is near a test (possibly inside suite/describe), then it must be prefixed with `^` and postfixed with `$`. This would run only the exact pattern (a single match). In this case there would be both namespace(s) and a test name. However, if the cursor is near a suite/describe (not a test), then it must be prefixed with `^` only (without `$`). This would allow running the nearest suite/describe along with its subtests. In this case there would be only namespace(s) without a test name.

I would probably issue a PR to fix this issue for Intern (also add the QUnit interface that I missed to support on the way). Similar thing could be made for Mocha and other "regex polyfill"-based runners.

**Comment by janko-m** [comment]
Thank you again for making the PRs, they have now both been merged. But I would like to leave this issue open to remind me to solve this for all other test runners that work with regexes (e.g. Jasmine should probably get it, and Ruby's Minitest has some inconsistencies).

**Comment by aaalsaleh** [comment]
Glad I could contribute back. Don't know about Minitest, but I think Jasmine's node runner doesn't support `^` and `$` anyway. If you take a quick look at its [source](https://github.com/jasmine/jasmine-npm/blob/856ef71d2a7bb201045692796b480ed0ce8d70b4/lib/filters/console_spec_filter.js#L4), you will realize that while `--filter` flag accepts a regex, it unfortunately escapes all special regex characters including `^` and `$`. Maybe this need to be brought to their attention as they need to leave escaping up to the user. However, I did notice Jasmine missing the test nearest in vim-test, so I see your point. Let me know if you need a hand.

**Comment by janko-m** [comment]
Hmm, I didn't know Jasmine runner supported regexes. Now when I followed your jasmine-npm link, I saw that I'm using a different Jasmine runner, [jasmine-node](https://github.com/mhevery/jasmine-node). Since jasmine-npm is in the "jasmine" organization, I'm guessing that is the right one?

**Comment by aaalsaleh** [comment]
I'll be honest, I never used Jasmine for any project. According to [their site](http://jasmine.github.io/edge/node.html) and [npm](https://www.npmjs.com/package/jasmine), I am guessing it is the official one (at least now). However, it might be the case that jasmine-node existed before it, as it is certainly older and has more stars/forks (but maybe outdated?).

Also, the runner I'm referring to still doesn't support regexes, as it escapes the filter (it is just `contains` currently). It has the potential though, and I've made a PR. In any case, you could still use the `--filter` flag without `^` and `$` if you choose to switch to it. Please note, I don't know which runner is preferred by those who actually use Jasmine.

**Comment by janko-m** [comment]
Replaced jasmine-node with jasmine-npm (https://github.com/janko-m/vim-test/commit/6049bcf88ef9eaa503c8ed04ddd21dac05c0712a), and checked that Minitest indeed has correct behaviour, so closing this.
