### ISSUE TITLE
Make Neovim's terminal configurable

### ISSUE THREAD

**Issue by janko-m** [janko-m/vim-test#121]
Currently the `neovim` strategy closes any open terminals, opens a new focused terminal, enters insert mode, and returns to the correct buffer on closing. I think that _at least_ the following behaviour should be configurable:
- focusing terminal or not
- focusing terminal only on failure
- closing terminal on success (otherwise stays open)
- running tests in background 
- insert mode or normal mode
- position where the terminal is opened (`botright`, `belowright`, ...)

There are two options for further action: (a) bring missing features to Neoterm, or (b) create a new plugin which 'does one thing and one thing right".

I would rather choose option (a) instead of "reinventing the wheel", since Neoterm already exists for some time so it likely got robust on user requirements.

**Comment by janko-m** [comment]
I briefly want to repeat what I said in https://github.com/janko-m/vim-test/issues/118 about Neoterm:

Even though Neoterm implements its own test runner support, so it might appear that Neoterm and Test.vim are two different alternatives, they are in fact *additive*. Neoterm currently has two responsibilities: (a) sending arbitrary commands to Neovim's terminal, and (b) building test commands. So even though in one part Neoterm *is* reinventing Test.vim, sending commands and controlling Neovim's terminal is an individual feature which we can use with Test.vim. This is what the [`neoterm`](https://github.com/janko-m/vim-test/blob/70181f8ec808dfa51675f14a5d0ea1959b880b8e/autoload/test/strategy.vim#L60-L62) strategy already does.

**Comment by dalizard** [comment]
@janko-m My understanding is that you'd rather have those configuration options handled by _neoterm_ and switching the `test#strategy` to `neoterm` instead of `neovim`. Is this correct?

**Comment by janko-m** [comment]
@dalizard Yes, that is the preferred option, provided that we can get all missing features from the list into Neoterm.

**Comment by emilsoman** [comment]
Correct me if I'm wrong, but I think the feature "focusing terminal or not" should be there for all strategies that can work in an "async" way. Shouldn't this be set by the user using a vim-test config rather than let the strategy handle it?

**Comment by emilsoman** [comment]
Also, I agree with you about the overlap of features in neoterm and vim-test. It'd be nice if I could just use vim-test along with neovim terminal instead of having to add neoterm to my setup.

**Comment by janko-m** [comment]
> Correct me if I'm wrong, but I think the feature "focusing terminal or not" should be there for all strategies that can work in an "async" way. Shouldn't this be set by the user using a vim-test config rather than let the strategy handle it?

You might be right, I haven't explored this possibility (as nobody requested it so far).

> Also, I agree with you about the overlap of features in neoterm and vim-test. It'd be nice if I could just use vim-test along with neovim terminal instead of having to add neoterm to my setup.

I think having a good `:terminal` wrapper plugin is very useful, because then it can be used with or without test.vim, and test.vim could just leverage all of the tiny details. As I mentioned, I would prefer to use a `:terminal` plugin that can be configured directly, but maybe still leave the `neovim` strategy who don't want to pull an external plugin.

**Comment by nomasprime** [comment]
@janko was open in normal mode implemented? Can't find in any docs.
