### ISSUE TITLE
With neoterm strategy python executable used for tests doesn't use virtualenv

### ISSUE THREAD

**Issue by purpleP** [janko-m/vim-test#125]
I've tried to switch to neoterm strategy a little while ago instead of neovim and I just noticed that this two behaves differently in this respect.

Neovim strategy seems to use python executable that was used when vim was launched.
Neoterm seems to use global python executable (it doesn't use python executable that was when vim was launched for sure).

**Comment by janko-m** [comment]
Hmm, yeah, Neovim uses a lot of Python, but it's strange that it uses the same Python executable. Sorry, I don't know a lot of Python, where are the *correct* Python executables located when you're inside a project root? I guess that generalizes to all Python test runners, right?

**Comment by janko-m** [comment]
I think this happens because Neovim's terminal might not load `.bashrc`/`.bash_profile`, so it doesn't have the virtualenv setup. Could you running each of this, and let me know if any finds the correct executable?

```
:terminal which python
:terminal bash -c 'which python'
:terminal bash --login -c 'which python'
```

**Comment by purpleP** [comment]
@janko-m Okay, so all this commands gives me correct result, they use python executable from virtual environment. Unlike neoterm's `T which python` which gives global python executable. So it's either a bug or a feature of neoterm.

**Comment by janko-m** [comment]
The only difference that I saw in Neoterm is that it's using `jobsend()` instead of `:terminal` or `terminal()`, but yeah, it would definitely be better to raise the issue there.
