### ISSUE TITLE
Not selecting proper executable for RSpec/Zeus on Yosemite

### ISSUE THREAD

**Issue by MichaelJosephKramer** [janko-m/vim-test#13]
When I tested this plugin on Yosemite with RSpec and Zeus, it didn't seem to pick up the existence of the .zeus.sock file. When I changed https://github.com/janko-m/vim-test/blob/master/autoload/test/ruby/rspec.vim#L20 to `if !empty(glob(".zeus.sock"))` it seemed to work properly.

I'm not sure this change would break anything, but I thought I'd see if anyone else had seen something like this before. Thanks!

**Comment by janko-m** [comment]
Thank you for reporting this. I like your suggestion, using `filereadable()` feels a bit strange anyway, because maybe the file doesn't have to be readable (since it's a socket). It just needs to exist, and this is exactly what `glob()` checks.
