### ISSUE TITLE
Are there plans for supporting rails 5 test runner?

### ISSUE THREAD

**Issue by jvanbaarsen** [janko-m/vim-test#130]
Since rails 5 is released, and they now have their own test runner (http://blog.bigbinary.com/2016/01/03/test-runner-in-rails-5.html). I was wondering, are there plans to support this in the future?

**Comment by janko-m** [comment]
Yes, I'm definitely for adding support for it, it should also be fairly easy to write, because it supports things like line numbers. Since I don't use Rails anymore and am a bit busy lately, I would be happy if someone could submit a PR.

**Comment by janko-m** [comment]
Added in https://github.com/janko-m/vim-test/pull/141

**Comment by jvanbaarsen** [comment]
❤️ Awesome! :D
