### ISSUE TITLE
Clear panel history for vimux

### ISSUE THREAD

**Issue by wilcus** [janko-m/vim-test#133]
Every time the output of the test appends into the terminal making difficult to navigate in tmux

Maybe you can use this command VimuxClearRunnerHistory to fix it (https://github.com/benmills/vimux/issues/26)

**Comment by janko-m** [comment]
Just using `VimuxClearRunnerHistory()` will clear everything that's out of the window, so that way part of the previous test output would remain. But if we clear the screen first, I think that should work good. I will push a fix shortly.

**Comment by janko-m** [comment]
Since someone might want this behaviour, for example if they want the `vimux` strategy to act the same way as the `normal` strategy, the Vimux clear screening will happen only when `g:test#preserve_screen` is explicitly set to `0`.

```vim
let g:test#preserve_screen = 0
```

**Comment by leighmcculloch** [comment]
Thanks for adding the `0` behavior. That's exactly what I wanted! ❤️Can we add it to the README? It's hard to find it.

**Comment by janko-m** [comment]
@leighmcculloch Added ✅

**Comment by leighmcculloch** [comment]
Thanks!!!

**Comment by leighmcculloch** [comment]
>The Vimux strategy will not clear the screen by default, but you can enable it by explicitly setting test#preserve_screen to 0.

I don't think this is accurate. It will shell `clear` it by default. Setting `1` will result in it not clearing but still echoing. Setting `0` will result in it not clearing, not echoing, but instead tmux-clearing.
