### ISSUE TITLE
Elixir umbrella support

### ISSUE THREAD

**Issue by kdisneur** [janko-m/vim-test#136]
Hi,

I tried to use your plugin to run tests inside an Elixir umbrella app but it doesn't seem to work.

It looks like `vim-test` run its test command using a relative path instead of an absolute path.  

Relative path:

```
mix test apps/app_name/test/models/model_name_test.exs
# ==> app1
# Test patterns did not match any file: apps/app1/test/file_test.exs
# ==> app2
# Test patterns did not match any file: apps/app1/test/file_test.exs
```

Absolute path:

```
mix test /Users/kdisneur/my_umbrella/apps/my_app/test/models/model_name_test.exs`
# ==> app1
# ....
#
# Finished in 0.1 seconds
#4 tests, 0 failures
#
# Randomized with seed 549588
# ==> app2
#
#
# Finished in 0.00 seconds
#0 failures
```

I also tried to run the command `mix test` using an absolute path, on a "normal" project. And it's working properly. 

Do you think it would be possible to use absolute path instead of relative path for Elixir tests ?

Thanks

**Comment by codeinabox** [comment]
Apologies for the delay in responding. Perhaps it would be possible to have absolute paths by overriding the args in `#build_args`

**Comment by janko-m** [comment]
Test.vim supports absolute paths:

```vim
let test#filename_modifier = ":p"
```

**Comment by dbernheisel** [comment]
Heads up for others in case they land here. If you want to start vim in the root of the project, but run individual tests or test files, then this snippet may help:

```vim
"  `.vim/after/ftplugin/elixir.vim` or `.vimrc`, whatever you prefer
function! ElixirUmbrellaTransform(cmd) abort
  if match(a:cmd, 'apps/') != -1
    return substitute(a:cmd, 'mix test apps/\([^/]*\)/', 'mix cmd --app \1 mix test --color ', '')
  else
    return a:cmd
  end
endfunction

let g:test#custom_transformations = {'elixir_umbrella': function('ElixirUmbrellaTransform')}
let g:test#transformation = 'elixir_umbrella'
```

This is adapted from [this comment](https://github.com/elixir-lang/elixir/issues/5650#issuecomment-272382922) by @wojtekmach, so all thanks should go to him.

I noticed that the color was missing when running tests, so I added the `--color` flag. This should work in Elixir 1.4+

**Comment by slashmili** [comment]
Just for the record, if you are using [Elixir 1.9](https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released), you don't need this `transformation` any more because Elixir mix test task understands the `apps/*/*` path([read more](https://dockyard.com/blog/2019/06/17/testing-in-umbrella-apps-improves-in-elixir-1-9))

the only config that you need to add is :
```
let g:test#filename_modifier = ":."
```
