### ISSUE TITLE
Feature Request: Failure Navigation

### ISSUE THREAD

**Issue by alex-netquity** [janko-m/vim-test#14]
It would be convenient if there was an option to feed failures to the quickfix window and to be able to navigate to the failure lines the usual quickfix mappings. I've seen other vim testing plugins do this.

**Comment by janko-m** [comment]
There already are even two ways to do it in vim-test:

1. Instruct vim-test to use the "make" strategy for running tests. That will select the appropriate Vim compiler (if it's available), and run the command with Vim's built-in `:make`, which loads the errors into a quickfix.

   ```vim
  let test#strategy = 'make'
   ```

2. Instruct vim-test to use the "dispatch" strategy for running tests. This uses [Dispatch.vim](https://github.com/tpope/vim-dispatch)'s `:Make` command, which is like an asynchronous `:make`.

   ```vim
  let test#strategy = 'dispatch'
   ```

It's included in the readme, but I will try to emphasize it more and explain what each strategy does.

**Comment by alex-netquity** [comment]
From what I can tell, using either `make` or `dispatch` feeds the entire result set into the quickfix window. Once there, it's possible to traverse the output as one might expect. This is different from what I meant.

I've seen other testing plugins feed the results into the quickfix window and allow the user to jump to the specific line on which each test failed using `:cnext` and `:cprevious`. These commands would navigate to the lines in the code where the failures occurred rather than navigating through the test output.

Is similar functionality available through vim-test?

**Comment by janko-m** [comment]
What test runner are you using with vim-test? When a quickfix list is loaded with the output, but the failures are not "linked" to the file locations, that happens when the "compiler" for that test runner doesn't exist. What Vim compilers do is they are able to read the test output, and create a quickfix list out of it (which can be traverse with `:cnext` and `:cprevious`).

Unfortunately, if the compiler doesn't exist for your test runner, vim-test can't provide it for you, because I would like to limit the scope of vim-test.

**Comment by janko-m** [comment]
Also, which other testing plugins do the quickfix? I would just like to take a look.

**Comment by alex-netquity** [comment]
I am using py.test for my test runner.

I can't recall exactly which testing plugin it was. It was some time ago. I believe it was https://github.com/reinh/vim-makegreen with the following command: `map <leader>dt :set makeprg=python\ manage.py\ test\|:call MakeGreen()<CR>`. At the time I was just using the Django test runner and not py.test.

**Comment by janko-m** [comment]
For Python there is a "pyunit" Vim compiler, maybe it works for py.test. Try

```vim
:compiler pyunit
:set makeprg=py.test\ your\ test\ command
```

Then run `:make` and see if the errors are loaded in the quickfix. If yes, I can configure vim-test to use "pyunit" compiler for Python tests.

**Comment by alex-netquity** [comment]
Unfortunately that did not produce new results.

![testresults]
(http://i.imgur.com/UaVcEp0.png)

It looks about the same when the failure is within the code being tested rather than in the test itself.

**Comment by nixon** [comment]
I'm using the vim-makegreen plugin as a custom strategy in vim-test with this in `~/.vimrc`:

```
function MakeGreenStrategy(cmd) abort
    call MakeGreen(join(split(a:cmd)[1:]))
endfunction
let g:test#custom_strategies = {'makegreen': function('MakeGreenStrategy')}
let g:test#strategy = 'makegreen'
```

It may also be necessary to have the following `~/.vim/ftplugin/python.vim`:

```
setlocal makeprg=nosetests
setlocal errorformat=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
```

This works for me to show the green or red bar at the bottom, plus the command output goes into the quickfix buffer.

**Comment by benoittgt** [comment]
In quite the same subject (tell me if I'm out of thread), is it possible to jump to the first failed test ? 

I'm working essentially with rspec and minitest.

**Comment by janko-m** [comment]
Well, since dispatch.vim generates a quickfix list with file locations from the test runner output, you can jump to the first failed test in the same way as you would jump to any first item in a quickfix list, with `:cc`.

**Comment by codeinabox** [comment]
I have noticed that this is a common question and until recently I didn't know you could leverage Dispatch and the compiler functionality to do so. If I get time I will create a PR that explains this in the README.

**Comment by janko-m** [comment]
@codeinabox I was hoping that people would just take a look at the documentation for each strategy to see if there is one that populates the quickfix list, but I guess it makes sense to explicitly document Dispatch.vim as it's probably the most comfortable strategy. You could also mention that `make`, `neomake`, and now `makegreen` strategies also populate the quickfix, and that they use Dispatch.vim to automatically find the compiler if Dispatch.vim is available.
