### ISSUE TITLE
How to blacklist test frameworks?

### ISSUE THREAD

**Issue by fortes** [janko-m/vim-test#144]
The Karma file pattern is a overly aggressive and keeps on matching in my mocha project, even though I've provided my own `file_pattern`. I've worked around this by setting Karma's file pattern to something bogus, but is there a way to either blacklist Karma or manually select the test framework? 

Thanks!

**Comment by janko-m** [comment]
I'm would like to avoid adding a blacklist if possible, ideally test.vim should be able to determine which runner you want to use, and if it doesn't it should be configurable.

The way that the Karma runner currently works is that it's activated if you have the `karma` executable inside the node_modules/ directory, so I'm assuming that you have Karma in your `package.json`. Can you think of any way that test.vim could determine whether certain JavaScript tests should be run using Karma or Mocha?

**Comment by fortes** [comment]
Well, that was it -- Karma had been installed into `node_modules`, although it wasn't used.

I don't have a good solution otherwise, checking for existence seems reasonable. It's easy enough to give a bogus regex matcher as well. Thanks.
