### ISSUE TITLE
TestNearest w/ MiniTest doesn't work when there is a question mark.

### ISSUE THREAD

**Issue by markbates** [janko-m/vim-test#15]
When there is a `?` in a describe block `TestNearest` doesn't run properly because the regular expression isn't properly escaped.

Here's an example:

```ruby
describe Foo do
  describe "#is_something?" do
    it "does something"do
      true.must_equal true
    end
  end
end
```

Output:

```
:!./bin/rake test TEST="test/models/foo_test.rb" TESTOPTS="--name='/Foo::#is_something?#test_\d+_does something/'"
Run options: "--name=/Foo::#is_something?#test_\\d+_does something/" --seed 1797

# Running:

Finished in 0.015936s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips 
```

I can easily reproduce this in MiniTest, I haven't tried rspec.

**Comment by janko-m** [comment]
Thank you for reporting :)

On RSpec there is no problem, because it accepts line numbers, and it internally calculates the nearest test.

**Comment by markbates** [comment]
Works great. Thanks for the quick turn around on this. It's a great plugin. Thanks for writing it.
