### ISSUE TITLE
Improve user experience and efficiency

### ISSUE THREAD

**Issue by purpleP** [janko-m/vim-test#150]
I'm using your plugin almost a year now and I think I know how it might be improved.

As a developer I want these things from test runner.

1. If all tests are green I just need to know that they are green. I don't need to see which ones have been actually runned, this plugin choses what I want to run very reliably. So maybe just show 'TEST ARE GREEN' in status line or in via message.
2. If tests aren't green - I need to know what have gone wrong. The best way to do that in vim is by using quickfix list, but I also like to see difference between expected and actual results. Can quickfix display multiline messages?
3. Lastly if tests aren't green most of the time I would need to debug them. So test runner should start tests and somehow capture the output (this should be possible, right?) and then use some user defined function to determine at each line is this a debugging session or not. For example I'm using python and pdb. Test runner could test whether or not the line starts with `pdb`. Or maybe there is some way to determine whether or not terminal waits for user input, I don't know.

I think I know vimscript enough now to implement this myself, but I have other issues at hand right now. So I'll just leave it there for your comments.

**Comment by purpleP** [comment]
Okay, I think to make this working against all strategies one can make a wrapper script like that
```zsh
"$@"
if [[ $? -eq 0 ]]; then
    sleep 1
    exit
fi
```
Which would take user some time to see the output and will terminate the session if everything worked fine.
This could be added to plugin as an option like `g:vim_test_use_wrapper`
The problem though is that I can't find how to close and delete terminal buffer on shell session exit. Can you help with that?

**Comment by janko-m** [comment]
@purpleP I'm sorry that I didn't have time to look at this yet, I'm lately pretty busy with other things. I will take a look as soon as I find time.

Just a quick question, what you're looking for sounds very much like Dispatch.vim, is there something that Dispatch.vim is missing?

**Comment by codeinabox** [comment]
Closing this for now but please re-open if you further questions
