### ISSUE TITLE
:TestLast Error "... test#run_last[7] ..test#shell: ...E731: using Dictionary as a String"

### ISSUE THREAD

**Issue by zhanjh** [janko-m/vim-test#151]
For phpunit, TestNearest and TestSuite works well
But TestLast, I got this error:

![image](https://cloud.githubusercontent.com/assets/10229945/20380106/e5808680-acda-11e6-8475-b49494551f9c.png)

**Comment by zhanjh** [comment]
temporary, change 
```
call test#shell(join(cmd))
```
to
```
execute "!" . join(cmd)
```
```
function! test#run_last(arguments) abort
  if exists('g:test#last_command')
    call s:detect_command_strategy(a:arguments)

    let cmd = [g:test#last_command]
    let cmd = cmd + a:arguments

    execute "!" . join(cmd)
    " todo
    " call test#shell(join(cmd))
  else
    call s:echo_failure('No tests were run so far')
  endif
endfunction

```

**Comment by janko-m** [comment]
It seems that this error is coming from [this line](https://github.com/janko-m/vim-test/blob/4261d90585a243759d6d808013ead247d95a4e3b/autoload/test.vim#L90). So it's either that your `g:test#custom_strategies` is not a dictionary (by default is should be `{}`), or, more likely, that your `g:test#strategy` is not a string.

**Comment by zhanjh** [comment]
I got this code from README.md

```
let test#strategy = {
  \ 'nearest': 'neovim',
  \ 'file':    'dispatch',
  \ 'suite':   'basic',
\}
```

so I changed "g:test#strategy" to "g:test#custom_strategies" and It worked.

Thanks

**Comment by janko-m** [comment]
Oh, I forgot that `test#strategy` can also be a dictionary. Then this seems to be a bug in test.vim, I will investigate.
