### ISSUE TITLE
The latest version (2016-11-28) will be failed to call minitest

### ISSUE THREAD

**Issue by xfyuan** [janko-m/vim-test#155]
When I updated vim-test to the latest version (2016-11-28), in a rails 4.x project which use minitest, vim-test always call bin/rails, so it will be failed to run a test.

**Comment by xfyuan** [comment]
When I check it out to commit #6537cf6e70c02fd8d52d8555aaa9b146cf82298c, it just works.

**Comment by janko-m** [comment]
@xfyuan That is really strange, [this](https://github.com/janko-m/vim-test/blob/d36a4a2404517aed5dc2653ef28c6a4b905d2d45/autoload/test/ruby/rails.vim#L5-L11) is the code that checks whether that `rails` runner should be used. You can see that, if either the Rails version is < 5 or the project isn't a Rails project, the `rails` runner shouldn't be activated.

Could you test what the `s:rails_function()` returns in your project? You can create a .vim file in your project, add the following function, then `:source` that file, and tell me what `:echo RailsVersion()` returns.

```vim
function! RailsVersion()
  if filereadable('Gemfile.lock')
    let gemfile_lock = system('cat Gemfile.lock')
    let version_string = matchstr(gemfile_lock, '\vrails \(\zs.+\ze\)')

    if !empty(version_string)
      let rails_version = matchlist(version_string, '\v(\d+)\.(\d+)\.(\d+)%(\.(\d+))?')[1:-1]
      call filter(rails_version, '!empty(v:val)')
      call map(rails_version, 'str2nr(v:val)')

      return rails_version
    end
  endif
endfunction
```

**Comment by xfyuan** [comment]
i got the result: [6, 3, 4]

**Comment by janko-m** [comment]
@xfyuan Thanks. Could you also post your `Gemfile.lock`? This is what this function is trying to parse the Rails version out of.

**Comment by xfyuan** [comment]
GIT
  remote: git://github.com/dylanjha/test_time_tracking.git
  revision: e12aeea65e85dcd5aea8ca7167ea01bfa05f2a91
  specs:
    test_time_tracking (0.0.1)

GIT
  remote: git@github.com:saharaying/mongoid_token.git
  revision: 5b141461f5356f597b3e805063336009bfe12221
  specs:
    mongoid_token (4.0.0)
      mongoid (~> 5.0)

GEM
  remote: http://gems.ruby-china.org/
  specs:
    aasm (4.4.1)
    actionmailer (4.2.7)
      actionpack (= 4.2.7)
      actionview (= 4.2.7)
      activejob (= 4.2.7)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7)
      actionview (= 4.2.7)
      activesupport (= 4.2.7)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-xml_parser (1.0.2)
      actionpack (>= 4.0.0, < 5)
    actionview (4.2.7)
      activesupport (= 4.2.7)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7)
      activesupport (= 4.2.7)
      globalid (>= 0.3.0)
    activemodel (4.2.7)
      activesupport (= 4.2.7)
      builder (~> 3.1)
    activerecord (4.2.7)
      activemodel (= 4.2.7)
      activesupport (= 4.2.7)
      arel (~> 6.0)
    activesupport (4.2.7)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    aescrypt (1.0.0)
    airbrake (5.6.1)
      airbrake-ruby (~> 1.6)
    airbrake-ruby (1.6.0)
    akami (1.3.1)
      gyoku (>= 0.4.0)
      nokogiri
    alipay (0.12.0)
    api_smith (1.3.0)
      hashie (>= 1.0, < 3.0)
      httparty
    arel (6.0.3)
    ast (2.3.0)
    autoprefixer-rails (6.3.4)
      execjs
    awesome_print (1.6.1)
    bcrypt (3.1.10)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    browser (1.1.0)
    bson (4.1.1)
    builder (3.2.2)
    bullet (5.0.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    byebug (8.2.1)
    cancancan (1.13.1)
    capistrano (3.2.1)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-rails (1.1.3)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano-sidekiq (0.5.4)
      capistrano
      sidekiq (>= 3.4)
    capistrano3-unicorn (0.2.1)
      capistrano (~> 3.1, >= 3.1.0)
    capybara (2.6.2)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.9.0)
      capybara (>= 2.3.0, < 2.7.0)
      json
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    carrierwave-mongoid (0.8.1)
      carrierwave (>= 0.8.0, < 0.11.0)
      mongoid (>= 3.0, < 6.0)
      mongoid-grid_fs (>= 1.3, < 3.0)
    carrierwave-qiniu (0.1.8)
      carrierwave
      qiniu (~> 6.4.2)
    childprocess (0.5.9)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    chunky_png (1.3.5)
    ckeditor_rails (4.5.10)
      railties (>= 3.0)
    cliver (0.3.2)
    coderay (1.1.0)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.2)
    connection_pool (2.2.0)
    css_parser (1.3.7)
      addressable
    cucumber (2.3.3)
      builder (>= 2.1.2)
      cucumber-core (~> 1.4.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      gherkin (~> 3.2.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.4.0)
      gherkin (~> 3.2.0)
    cucumber-rails (1.4.3)
      capybara (>= 1.1.2, < 3)
      cucumber (>= 1.3.8, < 3)
      mime-types (>= 1.16, < 4)
      nokogiri (~> 1.5)
      railties (>= 3, < 5)
    cucumber-wire (0.0.1)
    customerio (1.0.0)
      multi_json (~> 1.0)
    dalli (2.6.4)
    dalli-delete-matched (1.3.1)
      dalli
    database_cleaner (1.5.1)
    debug_inspector (0.0.2)
    diff-lcs (1.2.5)
    docile (1.1.5)
    docx_replace (1.0.4)
      rubyzip (~> 1.1, >= 1.1.6)
    domain_name (0.5.20161021)
      unf (>= 0.0.5, < 1.0.0)
    elasticsearch (2.0.0)
      elasticsearch-api (= 2.0.0)
      elasticsearch-transport (= 2.0.0)
    elasticsearch-api (2.0.0)
      multi_json
    elasticsearch-transport (2.0.0)
      faraday
      multi_json
    enumerize (2.0.0)
      activesupport (>= 3.2)
    erubis (2.7.0)
    eventmachine (1.0.9)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.6.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    fakeredis (0.5.0)
      redis (~> 3.0)
    fakeweb (1.3.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faye-websocket (0.7.5)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.3.5)
    ffi (1.9.10)
    font-awesome-rails (4.4.0.0)
      railties (>= 3.2, < 5.0)
    get_process_mem (0.2.0)
    gherkin (3.2.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    gyoku (1.3.1)
      builder (>= 2.1.2)
    hashie (2.1.2)
    highcharts-rails (4.1.5)
      railties (>= 3.1)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.10.2)
      multi_json (~> 1.0)
      multi_xml (>= 0.5.2)
    httpclient (2.7.1)
    httpi (2.4.1)
      rack
    i18n (0.7.0)
    jquery-rails (3.0.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery_file_download-rails (0.0.2)
      railties (>= 3.1.0)
    json (1.8.3)
    jwt (1.5.2)
    kgio (2.10.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.1.2)
      launchy (~> 2.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    m (1.4.2)
      method_source (>= 0.6.7)
      rake (>= 0.9.2.2)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    metaclass (0.0.4)
    method_source (0.8.2)
    mime-types (2.4.3)
    mini_magick (4.3.6)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    minitest-around (0.3.2)
      minitest (~> 5.0)
    minitest-hooks (1.4.0)
    mocha (1.1.0)
      metaclass (~> 0.0.1)
    momentjs-rails (2.11.0)
      railties (>= 3.1)
    moneta (0.8.0)
    mongo (2.3.0)
      bson (~> 4.1)
    mongoid (5.1.4)
      activemodel (~> 4.0)
      mongo (~> 2.1)
      origin (~> 2.2)
      tzinfo (>= 0.3.37)
    mongoid-autoinc (5.0.2)
      mongoid (~> 5.0)
    mongoid-compatibility (0.3.1)
      activesupport
      mongoid (>= 2.0)
    mongoid-grid_fs (2.2.1)
      mime-types (>= 1.0, < 3.0)
      mongoid (>= 3.0, < 6.0)
    mongoid-sadstory (0.0.2)
      mongoid
    mongoid_denormalize (1.0.0)
      mongoid (>= 4.0.0)
    mongoid_paranoia (0.2.1)
      mongoid (>= 4)
      mongoid-compatibility
    multi_json (1.12.1)
    multi_test (0.1.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    net-ping (1.7.8)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.2)
    netrc (0.11.0)
    newrelic_rpm (3.17.1.326)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    nori (2.6.0)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-identity (1.1.1)
      bcrypt-ruby (~> 3.0)
      omniauth (~> 1.0)
    omniauth-mingdao (0.2.1)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.0)
    omniauth-oauth2 (1.3.1)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-qq-connect (0.2.0)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.0)
    omniauth-renren-oauth2 (0.0.6)
      omniauth (~> 1.1)
      omniauth-oauth2 (~> 1.1)
    omniauth-weibo-oauth2 (0.4.0)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.0)
    origin (2.2.0)
    parallel (1.6.1)
    parallel_tests (2.4.0)
      parallel
    parser (2.3.1.2)
      ast (~> 2.2)
    pg (0.18.4)
    phantomjs (2.1.1.0)
    pingpp (2.0.15)
      json (~> 1.8, >= 1.8.1)
      mime-types (>= 1.25, < 4.0)
      rest-client (~> 1.4)
    pkg-config (1.1.7)
    poltergeist (1.8.1)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    posix-spawn (0.3.12)
    powerpack (0.1.1)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.3.0)
      byebug (~> 8.0)
      pry (~> 0.10)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    public_activity (1.4.3)
      actionpack (>= 3.0.0)
      activerecord (>= 3.0)
      i18n (>= 0.5.0)
      railties (>= 3.0.0)
    pusher (0.16.0)
      httpclient (~> 2.7)
      multi_json (~> 1.0)
      pusher-signature (~> 0.1.8)
    pusher-signature (0.1.8)
    qiniu (6.4.2)
      json (~> 1.8)
      mime-types (~> 2.4.3)
      rest-client (~> 1.8.0)
      ruby-hmac (~> 0.4)
    qunit-rails (0.0.7)
      railties
    rack (1.6.4)
    rack-attack (4.4.1)
      rack
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7)
      actionmailer (= 4.2.7)
      actionpack (= 4.2.7)
      actionview (= 4.2.7)
      activejob (= 4.2.7)
      activemodel (= 4.2.7)
      activerecord (= 4.2.7)
      activesupport (= 4.2.7)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-i18n (4.0.8)
      i18n (~> 0.7)
      railties (~> 4.0)
    rails_autolink (1.1.6)
      rails (> 3.1)
    railties (4.2.7)
      actionpack (= 4.2.7)
      activesupport (= 4.2.7)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.1.0)
    raindrops (0.17.0)
    rake (11.2.2)
    redcarpet (3.3.4)
    redis (3.3.1)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rmmseg-cpp-new (0.3.1)
    roadie (3.0.5)
      css_parser (~> 1.3.4)
      nokogiri (~> 1.6.0)
    roadie-rails (1.0.6)
      railties (>= 3.0, < 4.3)
      roadie (~> 3.0)
    rocket_pants (1.13.1)
      actionpack (>= 3.0, < 5.0)
      api_smith
      hashie (>= 1.0, < 3)
      moneta
      railties (>= 3.0, < 5.0)
      will_paginate (~> 3.0)
    roo (2.3.2)
      nokogiri (~> 1)
      rubyzip (~> 1.1, < 2.0.0)
    roo-xls (1.0.0)
      nokogiri
      roo (>= 2.0.0beta1, < 3)
      spreadsheet (> 0.9.0)
    rqrcode (0.9.0)
      chunky_png (~> 1.0)
    rqrcode_png (0.1.5)
      chunky_png
      rqrcode
    rubocop (0.40.0)
      parser (>= 2.3.1.0, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-hmac (0.4.0)
    ruby-ole (1.2.12)
    ruby-pinyin (0.5.0)
      rmmseg-cpp-new (~> 0.3.1)
    ruby-progressbar (1.7.5)
    rubyzip (1.1.7)
    rucaptcha (1.1.2)
      railties (>= 3.2)
    sass (3.4.22)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    savon (2.11.1)
      akami (~> 1.2)
      builder (>= 2.1.2)
      gyoku (~> 1.2)
      httpi (~> 2.3)
      nokogiri (>= 1.4.0)
      nori (~> 2.4)
      wasabi (~> 3.4)
    scss_lint (0.49.0)
      rake (>= 0.9, < 12)
      sass (~> 3.4.20)
    select2-rails (4.0.2)
      thor (~> 0.14)
    selenium-webdriver (2.52.0)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    sendcloud_rails (0.0.2)
      actionmailer (>= 3.2.13)
      json (>= 1.7.7)
      rest-client (>= 1.6.7)
    sidekiq (4.2.3)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-limit_fetch (3.4.0)
      sidekiq (>= 4)
    sidekiq-unique-jobs (4.0.18)
      sidekiq (>= 2.6)
      thor
    sidekiq_mailer (0.0.8)
      actionmailer (>= 3.0)
      activesupport (>= 3.0)
      sidekiq (>= 2.3)
    simplecov (0.12.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinon-rails (1.10.3)
      railties (>= 3.1)
    sitemap_generator (5.1.0)
      builder
    slop (3.6.0)
    spreadsheet (1.1.2)
      ruby-ole (>= 1.0)
    spring (1.6.3)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.1.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.8.1)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.5)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.1)
      execjs (>= 0.3.0, < 3)
    underscore-rails (1.8.3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    unicode-display_width (1.0.5)
    unicorn (5.1.0)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    unicorn-worker-killer (0.4.4)
      get_process_mem (~> 0)
      unicorn (>= 4, < 6)
    uniform_notifier (1.9.0)
    useragent (0.16.3)
    utf8-cleaner (0.1.1)
      activesupport
    wasabi (3.5.0)
      httpi (~> 2.0)
      nokogiri (>= 1.4.2)
    webshot (0.0.11)
      activesupport
      faye-websocket (~> 0.7.3)
      mini_magick (~> 4.3.3)
      poltergeist (~> 1.8.0)
    websocket (1.2.2)
    websocket-driver (0.6.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    wechat-utils (0.1.3)
      rest-client (~> 1.8)
    whenever (0.9.4)
      chronic (>= 0.6.3)
    will_paginate (3.0.7)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)
    will_paginate_mongoid (2.0.1)
      mongoid
      will_paginate (~> 3.0)
    wisper (2.0.0.rc1)
    wisper-minitest (0.0.3)
    wisper-sidekiq (0.0.1)
      sidekiq
      wisper
    writeexcel (1.0.5)
    wx_pay (0.5.0)
      activesupport (>= 3.2)
      rest-client (>= 1.7)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  aasm (~> 4.4.1)
  actionpack-xml_parser
  aescrypt
  airbrake (~> 5.6)
  alipay (~> 0.12.0)
  awesome_print
  better_errors
  binding_of_caller
  bootstrap-sass (~> 3.3, >= 3.3.6)
  browser
  bullet
  cancancan (~> 1.13.1)
  capistrano (~> 3.2.1)
  capistrano-bundler (~> 1.1.4)
  capistrano-rails (~> 1.1.3)
  capistrano-rvm
  capistrano-sidekiq
  capistrano3-unicorn
  capybara
  capybara-webkit
  carrierwave
  carrierwave-mongoid (~> 0.8.1)
  carrierwave-qiniu (~> 0.1.8)
  ckeditor_rails (~> 4.5.10)
  coderay
  coffee-rails (~> 4.1, >= 4.1.1)
  cucumber-rails
  customerio
  dalli
  dalli-delete-matched (~> 1.3.1)
  database_cleaner
  docx_replace
  elasticsearch
  enumerize
  factory_girl_rails
  fakeredis
  fakeweb (~> 1.3.0)
  font-awesome-rails (~> 4.4.0.0)
  highcharts-rails (~> 4.1.5)
  httparty (~> 0.10.2)
  jquery-rails (~> 3.0.1)
  jquery_file_download-rails (~> 0.0.2)
  json
  jwt
  launchy
  letter_opener (~> 1.1.2)
  m
  mini_magick (~> 4.3.6)
  minitest (~> 5.9)
  minitest-around
  minitest-hooks
  mocha (~> 1.1.0)
  momentjs-rails (~> 2.11)
  mongoid (~> 5.1, >= 5.1.4)
  mongoid-autoinc (~> 5.0, >= 5.0.2)
  mongoid-sadstory (~> 0.0.2)
  mongoid_denormalize (~> 1.0.0)
  mongoid_paranoia (~> 0.2.1)
  mongoid_token!
  net-ping
  newrelic_rpm
  omniauth-identity (~> 1.1.1)
  omniauth-mingdao (~> 0.2.1)
  omniauth-qq-connect (~> 0.2.0)
  omniauth-renren-oauth2 (~> 0.0.6)
  omniauth-weibo-oauth2 (~> 0.4.0)
  parallel
  parallel_tests
  pg
  phantomjs
  pingpp
  poltergeist (~> 1.8.1)
  posix-spawn (~> 0.3.11)
  pry-byebug
  pry-rails
  public_activity (~> 1.4.3)
  pusher (~> 0.16.0)
  qunit-rails
  rack-attack
  rails (~> 4.2, >= 4.2.7)
  rails-i18n
  rails_autolink
  redcarpet
  redis (~> 3.3.1)
  redis-namespace
  rest-client
  roadie (~> 3.0.5)
  roadie-rails (~> 1.0.6)
  rocket_pants (~> 1.13.1)
  roo (~> 2.3.2)
  roo-xls
  rqrcode_png (~> 0.1.5)
  rubocop
  ruby-pinyin (~> 0.5.0)
  ruby-progressbar (~> 1.7.5)
  rucaptcha
  sass-rails (~> 5.0, >= 5.0.4)
  savon (~> 2.11, >= 2.11.1)
  scss_lint
  select2-rails
  selenium-webdriver
  sendcloud_rails
  sidekiq (~> 4.2.3)
  sidekiq-limit_fetch (~> 3.4.0)
  sidekiq-unique-jobs (~> 4.0, >= 4.0.18)
  sidekiq_mailer
  simplecov (~> 0.12.0)
  sinon-rails
  sitemap_generator
  spreadsheet (~> 1.1.2)
  spring
  test_time_tracking!
  turbolinks (~> 2.5.3)
  uglifier (~> 3.0, >= 3.0.1)
  underscore-rails (~> 1.8, >= 1.8.3)
  unicorn (~> 5.1.0)
  unicorn-worker-killer
  useragent (~> 0.16.3)
  utf8-cleaner
  webshot (~> 0.0.11)
  wechat-utils (~> 0.1.3)
  whenever
  will_paginate-bootstrap (~> 1.0.1)
  will_paginate_mongoid (~> 2.0.1)
  wisper (= 2.0.0.rc1)
  wisper-minitest
  wisper-sidekiq (~> 0.0.1)
  writeexcel (~> 1.0.5)
  wx_pay (~> 0.5.0)

BUNDLED WITH
   1.13.6

**Comment by janko-m** [comment]
Thanks for the info. I did a wrong regex, which was matching `rails \(...\)` without the "beginning-of-line" anchor, so it caught the version of `autoprefixer-rails`. It should be good now.

**Comment by xfyuan** [comment]
Yes, it's fixed. Thanks for your so cool works and the great plugin, @janko-m
