### ISSUE TITLE
:TestNearest no longer working with pytest

### ISSUE THREAD

**Issue by sloria** [janko-m/vim-test#156]
https://github.com/janko-m/vim-test/commit/b36663f5e04a0545227dabe0ba6b04c2c8a8e113 caused a regression which breaks `:TestNearest` when using pytest.

The following test produces an error

```python
class TestVimTest:

    # Running :TestNearest on this method does not work
    def test_test_nearest(self):
        assert 2 + 2 == 4
```

```
|| ======================================== test session starts ========================================
|| platform darwin -- Python 3.5.2, pytest-2.9.0, py-1.4.30, pluggy-0.3.1 -- /Users/sloria/miniconda/bin/python3
|| rootdir: /Users/sloria, inifile: pytest.ini
|| plugins: cov-2.2.1
|| collecting 0 items
|| =================================== no tests ran in 0.01 seconds ====================================
|| ERROR: not found: /Users/sloria/tmp/scratch-1480522878/test_test.py::test_test_nearest
|| (no name '/Users/sloria/tmp/scratch-1480522878/test_test.py::test_test_nearest' in any of [<Module 'tmp/scratch-1480522878/test_test.py'>])
```

The problem is that the test class name (`TestVimTest`) is not included in the command. I'm not sure what it would take to add this, but I suggest reverting the above commit for the time being.

**Comment by janko-m** [comment]
@sloria Thanks for reporting

@purpleP Do you know what is the issue here?

**Comment by purpleP** [comment]
@janko-m @sloria the issue here is that class name was never included before. We would need to do a little more work and get nearest classname.

**Comment by purpleP** [comment]
@janko I don't know vim script well enough but it would be sufficient to determine whether nearest test is above/under or below the cursor and then search with regard for class name in that direction.
