### ISSUE TITLE
Failing to pass the correct TESTOPTS for minitest on a rails app

### ISSUE THREAD

**Issue by padi** [janko-m/vim-test#169]
**Update:**  TL;DR in light of further investigation: the generated `TESTOPTS` argument in minitest (`bin/rake test`) doesn't work well when https://github.com/metaskills/minitest-spec-rails is installed because although they are rails tests, the test names become `test_0001_method` instead of `test_method`.

----

Just installed your vim plugin today and I like it! 👍 

Using it in minitest on a rails app and it doesn't seem to pass the correct command lines args in`TESTOPTS` when using :TestNearest.

I have the following sample test (rewritten from non-open source code)

```ruby
require 'test_helper'

class SampleTest < ActiveSupport::TestCase
  setup do
    # do setup tasks
  end
  test ".a_class_method" do
     assert_equal Sample.a_class_method, "result"
  end
end
```

When I run `bin/rake test TEST=test/models/sample_test.rb` in the console, the test produces the name `SampleTest#_0001_\.a_class_method` but when I use :TestNearest in vim the following script is executed:

```vim
./bin/rake test TEST="test/models/deadline_test.rb" TESTOPTS="--name='/SampleTest#test_\.a_class_method$/'"
```

... which doesn't match since it has a number in between `test_` and `.a_class_method`

Not a vim script coder but upon checking https://github.com/janko-m/vim-test/blob/master/autoload/test/ruby/minitest.vim, it seems that it is trying to guess which category a file belongs to based on the patterns in https://github.com/janko-m/vim-test/blob/master/autoload/test/ruby.vim

What i think is the bug is that it's using the wrong regex in the following snippet from `minitest.vim`:

```vim
    # minitest.vim
    if syntax == 'rails'    " test('foo') { ... } 
      let test = ['test_'.substitute(test_name, '\s\+', '_', 'g')] " <<< probably matches this
    elseif syntax == 'spec' " it('foo') { ... }  
      let test = ['test_\d+_'.test_name] " <<< I want this
    else
```

I have an idea of how to fix this (e.g. just relax the regex to `['test_(?_\d+)_'.test_name]`, but I just want to put the issue here for feedback or if my suggestion is a good idea. Let me know if I can help. I'd be willing to fix this myself if I have the time now and I know how to test this.

**Comment by padi** [comment]
Another thing: Although I don't see any mention of  `minitest-rails`, I'm assuming your [Minitest section](https://github.com/janko-m/vim-test/wiki/Minitest) also uses minitest-rails.

I'm not sure why my version of `rake test` still spits out test names as `Sample#test_xxxx_method`. Will have to dig down what is missing with the pattern matching, if any.

**Comment by padi** [comment]
Update: made a sample rails 4.2.7.1 app (the one I'm using), created a sample test:

```ruby
# test/models/user_test.rb
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  test "the truth" do
    assert true
  end
end
```

And ran `rake test TESTOPTS="--verbose`:

```sh
Running via Spring preloader in process 66887
Run options: --verbose --seed 50286

# Running:

UserTest#test_the_truth = 0.01 s = .
```

Looks like it's ok. Slowly added gems one by one and discovered this after installing https://github.com/metaskills/minitest-spec-rails, which I also use:

```ruby
# modified Gemfile
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem "minitest-spec-rails" # <<<<<<<<< added this
end
```

And resulted in the numbers showing after `rake test TESTOPTS="--verbose`:
```sh
Running via Spring preloader in process 67093
Run options: --verbose --seed 19964

# Running:

UserTest#test_0001_the truth = 0.01 s = .
```

Looks like it's because https://github.com/metaskills/minitest-spec-rails doesn't work well with the current file pattern matching.

**Comment by codeinabox** [comment]
@padi are you still affected by this issue?

**Comment by padi** [comment]
@codeinabox It's been a while since I last had this issue since I'm working on a different project now.

My guess is that we can close this issue for now and have someone comment on this issue if they even encounter it again.

**Comment by workgena** [comment]
Just it case someone stumbled on this error.

After updating `minitest-spec-rails` from `5.4.0` to `5.5.0`, the `:TestNearest` started work correctly.
