### ISSUE TITLE
Incorporate vim-ember-cli-test-runner?

### ISSUE THREAD

**Issue by anhari** [janko-m/vim-test#170]
Is it possible to integrate the functionality in the following plugin into vim-test?

https://github.com/JarrodCTaylor/vim-ember-cli-test-runner

**Comment by janko-m** [comment]
It seems possible, yes. The Clojure testing support uses the fireplace.vim plugin, so whoever will implement this strategy can draw the inspiration from there.

Alternatively test.vim could copy the implementation from that plugin.

**Comment by jalcine** [comment]
Would probably be best to keep upstream support (and not maintaining two clones of code) if `vim-test` leverages `vim-ember-cli-test-runner` via its API.

**Comment by codeinabox** [comment]
Closing but please reopen if you need help creating a PR

**Comment by thiagofelix** [comment]
In case anyone still looking for some like this I've done one limited integration that you can reuse or build upon:
https://gist.github.com/thiagofelix/8b7f1df9c9bb066d97fa6324d4edf9c2
