### ISSUE TITLE
`:TestFile` results in `E117: Unknown function: test#run`

### ISSUE THREAD

**Issue by jalcine** [janko-m/vim-test#172]
My Neovim information:

```bash
NVIM v0.2.0-500-ge8899178
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170202-54894-1w0lbvk/build/config -I/tmp/neovim-20170202-54894-1w0lbvk/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170202-54894-1w0lbvk/build/src/nvim/auto -I/tmp/neovim-20170202-54894-1w0lbvk/build/include
Compiled by <scrubbed>@<scrubbed>

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e889917/share/nvim"

```

I built Neovim against Homebrew, using `brew install neovim --HEAD`.

---
My issue is that whenever I invoke any of the Ex commands for `vim-test`, I get errors about the functions defined in `autoload/test.vim` not being available. I checked my `rtp`:

```viml
echo stridx(&rtp, 'vim-test') > 0
> 1
```

Not sure what's going on. I'm using `vim-plug` as well. My configuration is available on here at https://github.com/jalcine/vimrc for more reference.

**Comment by codeinabox** [comment]
Are you still having this issue?

**Comment by jalcine** [comment]
Yes.

**Comment by janko-m** [comment]
I don't know what is causing this issue, but your Vim setup is somehow definitely preventing the `test#run()` function from being autoloaded from the `autoload/test.vim` file.

Considering that Test.vim is using the standard organizational conventions for creating Vim plugins, I doubt that the issue is caused by Test.vim. If you're certain the issue is in Test.vim, I would need you to create a minimal .vimrc that reproduces the issue.
