### ISSUE TITLE
Fish Shell support

### ISSUE THREAD

**Issue by leebrooks0** [janko-m/vim-test#18]
Hi

There is an issue with fish shell as fish doesn't currently support ```&&```  and requires ```and```
so ```clear && echo 'abc' && test``` should become ```clear and echo 'abc' and test```. 

I am using Vimux

**Comment by leebrooks0** [comment]
in fact some testing with Vimux directly shows that this is ideal ```clear; echo 'abc'; test```

**Comment by janko-m** [comment]
Thank you for reporting this. Yeah, it was pretty noobish from my side to chain the commands with '&&', ';' makes much more sense.

**Comment by leebrooks0** [comment]
Thanks, works perfectly now
