### ISSUE TITLE
Need help with issues or pull requests?

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#180]
As someone who has contributed, do you need any help with issues or pull requests?

**Comment by janko-m** [comment]
I sure do, and I couldn't possibly get a more suitable candidate! I added you to collaborators on vim-test 👍

**Comment by codeinabox** [comment]
💯

**Comment by codeinabox** [comment]
I've reached out to the authors of the pull requests not yet merged. If they don't get back to me am I am able to add additional commits to their PRs?

**Comment by janko-m** [comment]
@codeinabox As far as I know you cannot add commits to someone else's forks. What I normally do is use [hub](https://github.com/github/hub) to checkout their PR branch locally using `hub checkout https://github.com/janko-m/vim-test/pulls/<NUMBER>`, add additional commits, checkout to `master`, merge the created PR branch to `master`, and push `master` to GitHub.

This was I cannot review your additional fixes, though, but I really think that's fine, we can still agree on the PR ticket which changes still need to be made.

**Comment by codeinabox** [comment]
👌 

Is it possible to change the merge options just to be squash and merge?

**Comment by janko-m** [comment]
Yup, I'm fine with that :+1:
