### ISSUE TITLE
Question rahter than an issue

### ISSUE THREAD

**Issue by danazimi** [janko-m/vim-test#189]
Installed plugin on vim
Using django and would like to just run the default test. i.e 

> python manage.py test

I tried :testfile and all other available options, i get a different error compare to the out of the python manage test.

thanks.

**Comment by janko-m** [comment]
@dariushazimi What error are you getting? If you're not getting an error, what is the difference between the expected and the actual behaviour; what command did you expect test.vim to run, and what command did it actually run?

**Comment by codeinabox** [comment]
@dariushazimi is this issue still occurring?

**Comment by codeinabox** [comment]
Closing this issue for now. Feel free to reopen if it occurs again.
