### ISSUE TITLE
Error using neovim + neomake + vim-test + pytest

### ISSUE THREAD

**Issue by azmeuk** [janko-m/vim-test#192]
Hi. I encounter an issue when I try to use neovim 0.2.0, up-to-date neomake and vim-test (installed with Plug) and pytest 3.1.0.
I am not sure this bug report belongs here or at neomake's.

```bash
mkdir vim-test-test; cd vim-test-test
virtualenv -p python3 env
./env/bin/pip install neovim pytest
echo "def test_false(): assert False" > test_hello_world.py
nvim test_hello_world.py +TestFile
```
This produces the following error message: `Neomake: [2.3:1] Error during output processing for py.test: Vim(caddexpr):E378: 'errorformat' contains no pattern.`

I suppose the only relevant lines in `.config/nvim/init.vim` are:
```vim
let test#python#runner = 'pytest'
let test#strategy = "neomake"
```

How can I make things work?
Thank you for your help.

**Comment by codeinabox** [comment]
Do you get the issue with other test runners or just pytest?

**Comment by azmeuk** [comment]
pyunit and nose also produce this message

**Comment by codeinabox** [comment]
And if you use a different strategy do the runners worker fine?

**Comment by janko-m** [comment]
@codeinabox This is definitely specific to the `neomake` strategy. I'm assuming that it's failing to find the compiler and set an `errorformat`, but I don't have time ATM to check the implementation.

**Comment by codeinabox** [comment]
Yeah I was thinking the same. I'd have to try out the Neomake strategy but don't have time right now.

**Comment by azmeuk** [comment]
basic and neovim strategy works fine, neomake is the on which fails.

**Comment by codeinabox** [comment]
@markwoodhall I know you wrote this strategy, any pointers for diagnosing the issue?

**Comment by markwoodhall** [comment]
I can have a look, the implementation doesn't differ that much from the regular make strategy, they both try to figure out the compiler for the test command using vim dispatch.

**Comment by markwoodhall** [comment]
This actually works out of the box for me. Using the latest vim-test, neomake, vim-dispatch, and an appropriate pytest compiler. e,g, https://github.com/5long/pytest-vim-compiler, unless my understanding is completely wrong you need to have a valid compiler installed for the runner you are using. 

![Example](http://i.imgur.com/PCCNcx6.gif)

**Comment by azmeuk** [comment]
I plugged vim-dispatch and pytest-vim-compiler, set the `dispatch` strategy and it gives me another error.
![pytest](https://cloud.githubusercontent.com/assets/60163/26390877/ba6b693c-4060-11e7-9aae-6febcaa143ac.png)

**Comment by janko-m** [comment]
A while ago I made a [change](https://github.com/janko-m/vim-test/commit/49715a8d7fc84b6dd1311177e17c4d217a625b01) to how the `neomake` strategy gets executed, I think it should have resolved the issue. I will close this ticket for now, but feel free to reopen if the issue persists.
