### ISSUE TITLE
Add option to enable saving file before running test.

### ISSUE THREAD

**Issue by dominikduda** [janko-m/vim-test#200]
It is often for me that I run the test without saving changes and the unsaved version of is being run.

The first solution I can think of is adding `:wa<CR>` in front of each mapping. This could be switchable by some variable.

**Comment by janko-m** [comment]
Vim-test already has that functionality; if you've `set autowrite` in your `.vimrc`, vim-test will automatically assume you want test files to be automatically saved before running the test ([code](https://github.com/janko-m/vim-test/blob/4f5e175894ce1131437000d4ee5ed256261056ae/autoload/test.vim#L2-L4)). I picked this heuristics up from Dispatch.vim.

**Comment by dominikduda** [comment]
Oh didn't know about that option.

That solves the issue, thanks!
