### ISSUE TITLE
Read lines in a test file to determine runner

### ISSUE THREAD

**Issue by dstrunk** [janko-m/vim-test#215]
Great plugin, I love being able to use it for Elixir and Rails work without worrying about different configurations. I'm now building an app in PHP's Laravel, and got started with their integration testing framework, [Dusk](https://laravel.com/docs/5.4/dusk). Tests using Dusk look so similar to PHPUnit that I'm having a hard time figuring out how to conditionally run dusk based on these three conditions:

1. Existence of `laravel/dusk` in the `composer.json` file
2. Folder structure: dusk files will exist in the `Browser/YourTest.php` folder
3. A `use` statement in the test file, `use Laravel\Dusk\Browser;`

Is there some way (via the exposed API, preferably) to perform a regex on the currently open file to find a line and conditionally use a different runner?

I know number 1 can be solved using something like [`s:rails_version()`](https://github.com/janko-m/vim-test/blob/453db3d6dce641f91c66731aad971530729ca172/autoload/test/ruby/rails.vim#L39-L55), and I believe number 2 can be solved using regex.

Interested to see if number 3 could be solved, or if the first two are fine for adding a dusk runner to this project?

**Comment by codeinabox** [comment]
The third approach is very much possible, have a look what I did in https://github.com/janko-m/vim-test/blob/master/autoload/test/php/phpspec.vim

**Comment by janko-m** [comment]
@dstrunk It's not 100% correct to do `search()`, because you can call `:Test<Command>` from application files (which test.vim detects and runs that command on the last touched test file instead). It would be better to use `readfile()` and `filter()`:

```vim
function! test#php#laravel#test_file(file) abort
  return a:file =~# g:test#php#laravel#file_pattern
    \ && !empty(filter(readfile(a:file), 'v:val =~# "use Laravel\\Dusk\\Browser"'))
readfile(file)
```

**Comment by codeinabox** [comment]
@dstrunk let us know if you need any help implementing the test runner. If you create and test against some fixtures - see the examples in spec folder - it should be relatively straight forward.

**Comment by dstrunk** [comment]
Thanks, appreciate the pointers! I'll work on this in the afternoon and hope to submit a PR this weekend.
