### ISSUE TITLE
Registry of Errorformats Like Syntastic

### ISSUE THREAD

**Issue by trisys3** [janko-m/vim-test#220]
Basically, exactly what the title says: Would this plugin be able to get some `errorformat`s of its very own? This would be for the `make` strategies, so `make`, `dispatch`, `neomake`, and `makegreen`. I'm thinking if there is any place for `errorformat`s for tests, it would be in a plugin that was built around tests. This could also apply to things like `makeprg`, but I made this about `errorformat` because I think that is the hardest to do.

This is just a suggestion, I'm not sure how far this can even go, as `errorformat` is notoriously tricky for tests. Runners typically don't have a "compact" option like tools like `eslint`, and the format of the test output often seems designed to be extremely long, which makes it amazing for debugging, but not so much for automated tools. Factor in things like "1 failure out of 2 tests", many runners running the same thing even if no tests were found, and coverage tools like Istanbul, and you are going to have a very hard time getting an `errorformat`. Then again, I have only really dealt with JavaScript, maybe other languages have an easier time. The `rspec` plugin, for one, has an `errorformat` of its very own.

Even if `vim-test` didn't have `errorformat`s, it could have compiler setups, similar to `neomake_<filetype>_<linter>_maker`. This could at least have the `makeprg`/`executable`, or even an empty dictionary if the executable has the same filename as the runner. This way, users wouldn't have to dive into the wild, woolly world of compilers, as they do now to make `dispatch` work.

I have to say again, great work on the plugin. I looked at it a year ago when my company was looking into `karma` (too few people, too much code, yada yada), and I've been keeping up with it, and it just grows from strength to strength. It was great if a little small back then, but you guys certainly rose to the challenge. Great job!.

**Comment by codeinabox** [comment]
Based on earlier discussions, I believe that @janko-m wants to narrow the scope of this plug-in to just determining and launching tests runners with ideally zero config and delegate things like error format and compiler setup to plug-ins like [Dispatch](https://github.com/tpope/vim-dispatch)

**Comment by trisys3** [comment]
Would you at least consider not throwing an error when no "compiler" is found? I know this is a separate issue, but it would allay much of the concern that prompted opening this issue.

Right now, if you don't have a compiler file for whatever test runner you are using, you get an error. My thing is there aren't compiler files written for every single test framework out there, and the format is pretty arcane. Most of the time, it's probably better to just find another compiler file & copy most of it, but it's hard to find them, especially for newbies. You could just create a blank one, as long as your test runner has the same name as the executable and that executable is in the PATH or somehow findable by `vim-test`. Again, a newbie wouldn't know that, and may find it hard to figure out where to place the file even if he/she did.

Would you consider treating a nonexistent compiler file the same as an empty one, or is that all in `dispatch`'s domain?

**Comment by janko-m** [comment]
> I'm thinking if there is any place for errorformats for tests, it would be in a plugin that was built around tests.

I agree, I think it would make a lot of sense for test.vim to ship with test runner compilers that are otherwise missing. I'm open to accepting patches for all runners that don't yet have their compilers in the Vim distribution. That excludes e.g. `rspec`, whose compiler ships with `vim-ruby`, and `vim-ruby` is included in the Vim distribution, so it makes sense that the `rspec` compiler continues to be maintained there.

> This could also apply to things like `makeprg`, but I made this about `errorformat` because I think that is the hardest to do.

I think it would be most convenient if test.vim shipped with actual Vim compilers (`.vim` files located in the `compilers/` directory), which define both `makeprg` and `errorformat`. Now, `makeprg` won't actually be used, as test.vim is in charge of generating the test command, but dispatch.vim reads `makeprg` of each compiler to detect the correct compiler for the generated test command, and each of the "quickfix strategies" call dispatch.vim to do that.

> This is just a suggestion, I'm not sure how far this can even go, as `errorformat` is notoriously tricky for tests.

Yes, `errorformat` always looked extremely tricky for me, I never had to write one of my own. But that's the idiomatic Vim's way to parse the command output, and it's also what dispatch.vim recognizes, so I would still like to stick with it even if it will be tricky to write.

> I have to say again, great work on the plugin. I looked at it a year ago when my company was looking into karma (too few people, too much code, yada yada), and I've been keeping up with it, and it just grows from strength to strength. It was great if a little small back then, but you guys certainly rose to the challenge. Great job!.

❤️ 💚 💙

**Comment by trisys3** [comment]
I was trying to make a `jest` `errorformat`, now that we found out `angular` doesn't need `karma` and we will be switching to `react` soon anyway, and we all have `react` in projects at home. It's been slow going, since `jest` is worse than many runners in the non-computer-friendly department. If/when I ever get something usable, I will definitely submit a pull request for it.

**Comment by janko-m** [comment]
I'm closing this issue now as it's not actionable.

In conclusion, people are welcome to submit Vim compilers to test.vim for any test runner they want. These compilers should be located in the standard `compilers/` directory.
