### ISSUE TITLE
Feature request: Webdriver.io support

### ISSUE THREAD

**Issue by snoblenet** [janko-m/vim-test#225]
Is it possible to add this please?

The CLI options are:

- Run all tests using the default configuration file: `wdio wdio.conf.js`
- Run a named suite of tests using the default configuration file: `wdio wdio.conf.js --suite NAME`
- Run just one test using the default configuration file: `wdio wdio.conf.js ---spec FILE_PATH_RELATIVE_TO_PROJECT_ROOT`

(Change `wdio` to `./node_modules/.bin/wdio` to use local wdio.)

More details: http://webdriver.io/guide/testrunner/organizesuite.html

**Comment by codeinabox** [comment]
What file pattern do the tests have?

**Comment by snoblenet** [comment]
If I understand the question correctly, the `wdio.conf.js` configuration file exports a location for the test files. Webdriver.io will search the top-level of that directory plus any sub-directories for test files. Webdriver.io outsources the actual test running to Mocha, Cucumber or Jasmine.

**Comment by codeinabox** [comment]
Feel free to raise a PR or I could try picking it up when I've returned from holiday

**Comment by snoblenet** [comment]
cheers -- I've taken to just running Webdriver.io tests in a separate terminal tab -- that's working for me for the time being

**Comment by codeinabox** [comment]
I've made a start at adding support. Should be able to support TestFile and TestSuite. Will let you know when there is a branch you can test against.

**Comment by snoblenet** [comment]
awesome

**Comment by codeinabox** [comment]
Could you please try out the branch `feature/webdriver`

**Comment by snoblenet** [comment]
will do thx

**Comment by snoblenet** [comment]
Thanks for all your work on this.
I changed my `init.vim` to:
```
Plug 'janko-m/vim-test', { 'branch': 'feature/webdriver' }
let test#javascript#webdriver#file_pattern = '.js'
let g:test#runner_commands = ['Mocha', 'WebdriverIo']
```
I then CDd into the plug-in directory, noticed that `master` was still checked out, and pulled and checkout `feature/webdriver` instead manually.

I restarted Neovim, entered a spec file in a Webdriver.io project, and ran `:WebdriverIo`.

I got the message: `E:492 Not an editor command`.

By contrast, when I entered `:Mocha`, it attempted to run the file.

Inside the file, I then tried entering `:TestFile`, but I got a `Not a test file` error.

The full path to the file would be described by `/test/**/**/*.js`.

Any suggestions?

**Comment by janko-m** [comment]
@snoblenet First of all, the command name is `WebdriverIO`, the `IO` is uppercase.

It seems that the file pattern should probably be improved, but great that you found how to change it.

Do you have `webdriverio` specified in your `package.json`, and `wdio.conf.js` at the root of your working directory?

**Comment by snoblenet** [comment]
Thanks. I changed my `init.vim` to:
```
let g:test#runner_commands = ['Mocha', 'WebdriverIO']
```
When I enter `:WebdriverIO` it now tries to run the test file using Webdriver.io (though it currently fails as it looks for a global `wdio` and I always install and use these things locally. I can dig into that myself shortly.

When I enter `:TestFile`, it still says `Not a test file`.

I have `webdriverio` specified in my `package.json`, and `wdio.conf.js` is at the root of my working directory.

One thing: `webdriverio` is in `dependencies` not `devDependencies` as I'm working on a test harness that is a seperate application to the application I am testing. Does that matter?

Do you recommend I make changes to the file pattern?

**Comment by janko-m** [comment]
> though it currently fails as it looks for a global `wdio` and I always install and use these things locally

The runner *should* automatically use `node_modules/.bin/wdio` if it exists, and only in case it doesn't exist use the global `wdio`. I'm wondering why doesn't it work 🤔

> When I enter `:TestFile`, it still says `Not a test file`.

Ooh, I see that you set `webdriver`:

```vim
let test#javascript#webdriver#file_pattern = '.js'
```

But it should actually be `webdriverio`:

```vim
let test#javascript#webdriverio#file_pattern = '.js'
```

> One thing: webdriverio is in dependencies not devDependencies as I'm working on a test harness that is a seperate application to the application I am testing. Does that matter?

It doesn't matter, test.vim will pick it up in either case.

> Do you recommend I make changes to the file pattern?

No, the file pattern you set is fine and will work, I was suggesting changing the default file pattern in https://github.com/janko-m/vim-test/pull/236.

**Comment by snoblenet** [comment]
I changed my `init.vim` to:
```
let test#javascript#webdriverio#file_pattern = '.js'
```
(I also re-ran `:PlugInstall` though I doubt that had an effect.)

`:TestFile` is now working. Thanks! I'll test the other commands momentarily.

**Comment by snoblenet** [comment]
The following confirmed to work too:

- `:TestSuite`
- `:TestLast`
- `:TestVisit`

(Didn't test `:TestNearest` as you don't run unit tests in Webdriver.io so you generally have just one long test per file.)

**Comment by codeinabox** [comment]
I have changed the pattern to  `g:test#javascript#webdriverio#file_pattern = '\vtests?/.*\.js$'`.

Did you get it to call `node_modules/.bin/wdio` in the end?

**Comment by snoblenet** [comment]
Yes it's using my local `wdio` now. Thanks. (Can't remember what step immediately came before that change sorry.)

**Comment by codeinabox** [comment]
This feature has now been merged into master. Thank for helping to test it.
