### ISSUE TITLE
Feature request: TestLast on save 

### ISSUE THREAD

**Issue by atgiovannini** [janko-m/vim-test#226]
Could be a nice feature, to run the last test on saving any project file.

**Comment by janko-m** [comment]
A [PR](https://github.com/janko-m/vim-test/pull/221) is already open for making it easy to add such and autocommand, I will notify you when it's merged.

**Comment by janko-m** [comment]
If you want to run the last test on saving any project file, you can setup the following autocommand:

```vim
augroup test
  autocmd!
  autocmd BufWrite * if exists('g:test#last_command') | TestLast | endif
augroup END
```

Alternatively you can use `test#exists()` for a more conservative approach, see the [Autocommands](https://github.com/janko-m/vim-test#autocommands) section.
