### ISSUE TITLE
Unable to run current spec

### ISSUE THREAD

**Issue by userrails** [janko-m/vim-test#228]
Hi, I am using `vim-test` for `unit-test` in `ruby on rails`.

__Steps__

- Run `TestNearest`

__Exptected__

- It should run current unit test that my cursor is focused on

__Current__

- It looks like running current unit test, but will actually runs Current `TestFile`.

> NOTE: it is working as expected with `Rspec` though.

**Comment by janko-m** [comment]
Can you tell me which command is being run? You can see that if you use the `basic` strategy, the test command will be printed out. Does the test not include line number/regex, or it includes it but the test runner doesn't detect it. Is `rake test` or `rails test` being run?

**Comment by janko-m** [comment]
Closing due to lack of information.
