### ISSUE TITLE
Integrate with Rails.vim projections

### ISSUE THREAD

**Issue by janko-m** [janko-m/vim-test#229]
Test.vim already has projectionist.vim integration, so if you're on an application file, and an alternate file is defined and it's a test file, running `:TestFile` will automatically run the test command on the alternate file.

This, however, doesn't work with projections defined by rails.vim, because it seems that rails.vim doesn't actually extend the projectionist registry with its Rails-specific projections (it doesn't call `projectionist#append` anywhere).

**Comment by benoittgt** [comment]
Thanks a lot. Works perfectly now !
