### ISSUE TITLE
pytest: nearest: picks up inline class

### ISSUE THREAD

**Issue by blueyed** [janko-m/vim-test#232]
Given the following Python code:

```python
def test_foo():
    class CustomException(Exception):
        pass
    mocker.patch('some.module', side_effect=CustomException())

    assert something
```

`echo test#python#pytest#build_position('nearest', {'file': bufname('%'), 'line': line('.'), 'column': col('.')})` at the end of the function will result in `['t.py::CustomException']`.

It should use `test_foo` instead.

**Comment by codeinabox** [comment]
Thanks for reporting this. I will try to look into this week but please free to raise a PR.

**Comment by codeinabox** [comment]
I have recreated the issue. To confirm the issue only happens when it is run inside the test?

**Comment by blueyed** [comment]
> To confirm the issue only happens when it is run inside the test?

Yes, somewhere below the `CustomException`.

**Comment by codeinabox** [comment]
Closing as the PR has been merged in
