### ISSUE TITLE
Mocha tests result in "Not a test file"

### ISSUE THREAD

**Issue by dfalling** [janko-m/vim-test#233]
My Mocha tests are located throughout my project, adjacent to the file they're testing,with a `spec.js` suffix.  I modified the Mocha runner pattern to `let test#javascript#mocha#file_pattern = '_spec\.js'`.

Running `:TestFile` results in `Not a test file`.  Additionally, I don't seem to have any of the runner commands (`:Mocha`, `:RSpec`, `:ExUnit`, `:Nose`).  I installed vim-test via vim-plug.

Do you have any suggestions for troubleshooting this?

Thanks!

**Comment by codeinabox** [comment]
Is Mocha listed in your package.json? Could you please provide the path relative to the project root of the test you are trying to run.

**Comment by dfalling** [comment]
Mocha's listed in my package.json's devDependencies:
```javascript
devDependencies: {
...
  "mocha": "^3.2.0",
...
}
```

How is the project root determined?  I have a mono repo that contains 3 separate projects: `(git root)/frontend/app/models/user.spec.js`.

**Comment by codeinabox** [comment]
Project route is determined as follows https://github.com/janko-m/vim-test/blob/c60a0e2679ecde4a929cbabf6573ba67524f1adf/README.md#working-directory

**Comment by dfalling** [comment]
Ah, I was definitely cd'ed into the project.  Hard setting the project root as well didn't make a difference.

**Comment by codeinabox** [comment]
What if you try this command before running a test?

```viml
let g:test#javascript#mocha#file_pattern = '.*\.spec\.js'
```

**Comment by dfalling** [comment]
That was it.  Thanks!

**Comment by gjunkie** [comment]
@codeinabox I'm having this same issue as @dfalling described. All my test files are adjacent to the file they're testing, they are all named `tests.js`, but "Not a test file" gets thrown every time I run `:TestFile`. I have mocha declared in my devDependencies in my package.json at the root of my project, and I'm cd-ed and working at my project root.

Running `echo expand('%') =~ '\vtests?/.*\.(js|coffee)$'` returns 0.

Any help would be appreciated. Thanks!

**Comment by dfalling** [comment]
@gjunkie does modifying @codeinabox's fix for me work?
```vim
let g:test#javascript#mocha#file_pattern = '.*\.tests\.js'
```

**Comment by gjunkie** [comment]
@dfalling I tried that, it unfortunately didn't help. I think the main issue might be that the echo command returns 0, which I believe means that it can't find any test files? Not sure...
