### ISSUE TITLE
How to disable change directory when running test?

### ISSUE THREAD

**Issue by taufek** [janko-m/vim-test#240]
I'm using vim-tmux-runner dispatch strategy (`test#strategy = "vtr"`) to run my test in tmux pane that runs a docker container. In the container, my project located on different path from the host machine. Whenever I run the tests, seems like `vim-test` will automatically change to my project directory according to my host machine which resulted as "no such file or directory" error as shown below.

<img width="645" alt="chdir" src="https://user-images.githubusercontent.com/10803354/32405873-b933f966-c1a8-11e7-9ebd-07867e9b3105.png">

Is there a way to disable that change directory that I highlighted in above screenshot?

**Comment by codeinabox** [comment]
I know this was discussed in #183 if that helps

**Comment by taufek** [comment]
Thanks @codeinabox .

I've created a PR to fix my issue. Thoughts anyone?

https://github.com/janko-m/vim-test/pull/241

**Comment by codeinabox** [comment]
Thank you. @janko-m is probably the best one to comment on this.

**Comment by codeinabox** [comment]
@janko-m what are your thoughts on this.

**Comment by janko-m** [comment]
Sorry, I haven't been able to look this yet. At the moment I'm more inclined to making automatic `cd`-ing *opt-in* rather than opt-out, as it was added as a convenience in case you're using something like `vtr` and in the vim-test's tmux pane you wander off to some other directories.

**Comment by janko-m** [comment]
Note that here I don't mean the `cd`-ing that happens on the test.vim level (in `autoload/test.vim`), I mean the `cd`-ing that happens on the strategy level (in `autoload/test/strategy.vim`).

**Comment by janko-m** [comment]
@taufek Let me know if https://github.com/janko-m/vim-test/pull/259 resolved the issue.

**Comment by taufek** [comment]
@janko-m , it does. Thanks for helping me to fix this. 👍
