### ISSUE TITLE
Broken Python patterns for nearest tests

### ISSUE THREAD

**Issue by michaelmanganiello-eb** [janko-m/vim-test#243]
Both #235 and #239 are based on some wrong assumptions, and has made vim-test to fail in some scenarios, at least for my particular usage:

1. We shouldn't have to change our existing code to prefix test classes with `Test`, when existing test classes with `Test` somewhere in their names already qualify for our test runners.
2. #239 forces us to use `import unittest`, and not even considers partial imports like `from unittest import TestCase`.
3. No support for test class inheritance, unless the child class is also prefixed with `Test`.

IMHO, these scenarios are more common than bug #232.

**Comment by codeinabox** [comment]
Thank you for the bug report, could you please include an example of the test you are trying to run and we can fix the implementation against it.

**Comment by michaelmanganiello-eb** [comment]
Using [unittest docs](https://docs.python.org/2/library/unittest.html) as an example, these are some failing scenarios:

```
import unittest

class SimpleWidgetTestCase(unittest.TestCase):
    pass

class DefaultWidgetSizeTestCase(SimpleWidgetTestCase):
    def test_widget(self):
        pass

# Should result in DefaultWidgetSizeTestCase:test_widget
```

```
from unittest import TestCase

class DefaultWidgetSizeTestCase(TestCase):
    def test_widget(self):
        pass

# Should result in DefaultWidgetSizeTestCase:test_widget
```

**Comment by codeinabox** [comment]
I've created a branch to fix it, could you please give it a try.

**Comment by codeinabox** [comment]
Please let know if you have any further feedback on #245 otherwise shall merge during the week.

**Comment by codeinabox** [comment]
I've merged the fix into master. Could you please let me know if you still have issues.

**Comment by janko-m** [comment]
I will close this, as https://github.com/janko-m/vim-test/pull/245 should have resolved the issue.

**Comment by chrisnovak** [comment]
Looks like this is still an issue.
