### ISSUE TITLE
NeoVim terminal closes a window

### ISSUE THREAD

**Issue by arusahni** [janko-m/vim-test#25]
Hi,
I'm currently using NeoVim in conjunction with pytest. When I set the test strategy to be "neovim", the terminal opens just fine. However, it takes over the active split and, upon test completion, the terminal and the split get closed.  Is there a way to direct the terminal to open in a new split?

Thanks!

**Comment by janko-m** [comment]
Recently the [neoterm](https://github.com/kassio/neoterm) project emerged, which is a wrapper around Neovim's `:terminal` feature. The support was added just a few days ago to vim-test (`let test#strategy = "neoterm"`). As I understood, Neoterm allows some customization of how Terminal is opened, so maybe you could take a look to see if it suits your needs.

**Comment by janko-m** [comment]
In general, it's outside of vim-test's scope to implement customization of strategies. Strategy plugins should provide their own customization and configuration, and should expose a simple interface for vim-test to use.

**Comment by arusahni** [comment]
No worries. Thanks!

**Comment by rschmukler** [comment]
@janko-m how would someone create a custom strategy for vim-test? Specifically, when using something like Vundle which uses version control to manage plugins (so you don't want to edit the `strategies.vim` file)? How do we create a custom strategy given that it appears to be using `test#strategy#<name>` namespacing?


Apologies if this is a stupid question, I've never done anything with vimscript, but would love my pane to not close on test.

**Comment by janko-m** [comment]
Thank you for noticing, this indeed is something I haven't given any thought. Try to put the strategy function inside of `~/.vim/autoload/test/strategy.vim`, hopefully Vim will autoload your file as well as mine. But I should definitely make it so that you can put the strategy inside of `.vimrc`.

**Comment by rschmukler** [comment]
@janko-m Thanks for the quick response! I initially tried that, and sadly it didn't seem to work. Maybe double check before you do any work to re-factor (again, I am an absolute novice when it comes to vimscript/how vim plugins load), but it'd definitely be idea if we could put custom functions in our `.vimrc`.

**Comment by zenbro** [comment]
@rschmukler I wrote a [blog post](https://zenbro.github.io/2015/08/08/overriding-default-vim-test-strategies.html) about overriding vim-test strategies. Hope it helps.

**Comment by janko-m** [comment]
@zenbro Thanks for discovering that! I tried the same thing before, but with defining a new strategy, and I get an error that I have to define it in the appropriate script file, but when overriding an existing strategy it works.

But I think it still isn't an ideal solution for @rschmukler, because he wants to add a new custom strategy, and I still didn't solve #28.

**Comment by lee-kagiso** [comment]
@zenbro thanks, super useful!

**Comment by lee-kagiso** [comment]
@janko-m why don't we just update the neovim strategy to use @zenbro's solution?

**Comment by janko-m** [comment]
Good idea, for some reason it hasn't come to my mind even though I've read the blog post, I updated it now.

**Comment by lee-kagiso** [comment]
Now it works great, except for the following:

if you have 2 or more windows open and you run your tests from a window that isn't leftmost, the focus/cursor switches to the left most window
