### ISSUE TITLE
Won't run elixir tests anymore

### ISSUE THREAD

**Issue by randre03** [janko-m/vim-test#252]
I've been using vim-test now for a little while and it has always worked for elixir projects...until this morning. Not sure what has changed and I've tried every permutation I can think of - using a different runner, using with vim-dispatch, using without vim-dispatch. Nothing is working.

As far as I can tell, the issue appears to be related to vim-test not being able to locate/read the mix.exs file. The output from running any of vim-test's test commands shows that it tried to run `elixir [testfile]` instead of `mix [testfile]`. This results in the runner complaining that ExUnit.start() must be called in order to run the tests. I can confirm I have a mix.exs file.

One thing to note is that when I created a 'dummy' mix project, ran `mix compile` and then tried to run the test, it worked. But when I tried it a second time...same error as above.

My current settings are:
     let test#strategy = 'neovim'
     let g:test#preserve_screen = 1

I have also tried with and without `let g:dispatch_compilers = { 'elixir': 'exunit' }`, but still have the same issue.

I have no problems running the above settings within a ruby project.

**Comment by codeinabox** [comment]
What has changed since the Elixir tests stopped working? Did you upgrade the plugin or have you changed the directory structure or naming in your project? Could you provide some examples of the full pathname of tests you are trying to run

**Comment by randre03** [comment]
I just figured it out. It's all tied to cwd.

I have an informal umbrella project - three different mix projects in same parent directory
```
+-- game
|   +-- dictionary
|   +-- hangman
|   +-- text_client
```
They are all related, but each has its own separate `mix.exs` file.

If I open neovim inside one of the mix projects, then everything works as expected. But if I try to run vim-test after opening neovim in the 'game' directory - I get the behavior described above. I believe this is due to there not being a `mix.exs` in the game directory.

I assume that if I had organized this as an umbrella project from the start, then the issue would not have appeared to begin with.
