### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by LandonSchropp** [janko-m/vim-test#254]
At work, we do all of our local development inside of Docker containers. Is there an easy way to configure vim-test to prepend Docker to the test commands? Barring that, can I override the command vim-test uses and set my own?

**Comment by janko-m** [comment]
@LandonSchropp Yes, you can register a [transformation function](https://github.com/janko-m/vim-test#transformations) that will be applied for each test command.

```vim
function! DockerTransform(cmd) abort
  # return test command wrapped in docker stuff
endfunction

let g:test#custom_transformations = {'docker': function('DockerTransform')}
let g:test#transformation = 'docker'
```

**Comment by LandonSchropp** [comment]
Awesome! Thank you.

**Comment by jvanbaarsen** [comment]
@LandonSchropp Did you manage to get this to work?

**Comment by LandonSchropp** [comment]
@jvanbaarsen: I'm using Neovim, so I went ahead and wrote my own custom functions that call `terminal` to give myself a bit more control.

```function! RunTests(command_variable)
  if !exists(a:command_variable)
    echo 'The ' . a:command_variable ' variable must be set to run this command.'
    return
  endif

  execute 'let l:command = ' . a:command_variable
  let l:command = substitute(l:command, '$file', expand('%'), 'g')

  split
  execute 'terminal ' . l:command
endfunction

function! TestSuite()
  call RunTests('g:test#suite_command')
endfunction

function! TestFile()
  call RunTests('g:test#file_command')
endfunction
```

I then mapped those functions to keyboard shortcuts.

**Comment by Artem-Schander** [comment]
For the googlers:
You could create a local vimrc and add something like `let g:test#php#phpunit#executable = 'docker-compose exec app vendor/bin/phpunit'` in it.
Worked for me.

**Comment by felippemr** [comment]
Kind of a hack but, if you are using neoterm and ssh into the container you can still use the default executor since vim-test will paste the command in the neoterm opened. I tested it and it worked for me.
