### ISSUE TITLE
Is there any smarter way to autodetect `Rake::TestTask`?

### ISSUE THREAD

**Issue by ajvondrak** [janko-m/vim-test#257]
Per this check in minitest.vim, vim-test will only recognize when `Rake::TestTask` is in the top-level Rakefile: https://github.com/janko-m/vim-test/blob/387b1ac70b9c6a88bb070fca5d670223c84aeab9/autoload/test/minitest.vim#L51

My Rakefile was growing large, so I split it up using `Rake.add_rakelib('tasks')` + a tasks/test.rake file that instantiates the `Rake::TestTask`. Because of the separate file, my test suite went from using `rake test` to using`ruby -I` unexpectedly. This was a mild annoyance because my test suite happened to look for the use of `TEST=...` for turning coverage on/off.

In principle, you could define rake tasks in _any_ \*.rake file using `Rake.add_rakelib`. Is it worth doing a (potentially expensive) equivalent of `grep Rake::TestTask **/*.rake` instead? Any better alternatives? 🤔 

Thanks for the great plugin!

**Comment by janko-m** [comment]
Yes, detecting that would definitely make sense. I think the safest option would be to look for `Rake::TestTask` in any `**/*.rake` files in the project, in addition to the `Rakefile`.

For now you should be able to fix this with

```vim
let g:test#ruby#minitest#executable = "rake test"
" or
let g:test#ruby#minitest#executable = "bundle exec rake test"
```

(You can add that to a project-local `.vimrc` and make sure you've `set exrc` in the global `~/.vimrc`.)

**Comment by ajvondrak** [comment]
Oh cool, that's a better idea than what I was doing, haha. The way I had gone about it was to put a comment in my Rakefile like:

```ruby
# vim-test: Rake::TestTask
# https://github.com/janko-m/vim-test/issues/257
```

Makes more sense to address it on the vimrc level (until the detection is improved, anyway).

**Comment by janko-m** [comment]
I had to revert this change, see https://github.com/janko-m/vim-test/issues/260 for the discussion.
