### ISSUE TITLE
Can't make it work: not an editor command

### ISSUE THREAD

**Issue by hoetmaaiers** [janko-m/vim-test#262]
Hi,

I tried all possible solutions but nothing seems to fix my problem:

I have succesfully installed vim-test through plug. When I run TestNearest I receive the error `E492: Not an editor command: Dispatch node_modules/.bin/mocha ...` However the binary is present at this path. Is this a know issue?
  

<img width="935" alt="fg" src="https://user-images.githubusercontent.com/468045/34611438-c6e0d91e-f225-11e7-85c6-5ebaf19a3855.png">

**Comment by codeinabox** [comment]
Which strategy have you selected?

**Comment by janko-m** [comment]
@hoetmaaiers You must have selected a strategy that requires having vim-dispatch installed, and the failure happens when vim-test calls the `:Dispatch` Vim command, which doesn't exist if you don't have vim-dispatch installed.

**Comment by hoetmaaiers** [comment]
This was exactly my problem. Thank you @janko-m !!
