### ISSUE TITLE
What is the file pattern for tests ending in '.spec.js'?

### ISSUE THREAD

**Issue by mhanberg** [janko-m/vim-test#271]
Hi, love the plugin, have been able to use it with ExUnit in Elixir to great success, but I can't seem to get the file pattern to match the mocha specs that I'm working with.

The file names use a `<spec name>.spec.js` pattern.

Thanks!

Edit: This has been observed on:
Vim: 8.0.1438
Windows Subsystem for Linux, Ubuntu: 16.04.3

**Comment by codeinabox** [comment]
It matches anything in a directory called "test" or "tests":

```viml
  let g:test#javascript#mocha#file_pattern = '\vtests?/.*\.(js|jsx|coffee)$'
```

**Comment by mhanberg** [comment]
Ok, that’s making sense to me now. 

Should it only find this directory under the test(s) directory? Or should it find a test in a structure like so `test/controllers/auth/auth-controller.spec.js`?

**Comment by codeinabox** [comment]
I believe that regular expression should supported nested directories like the example you have given. I double checked the Mocha documentation and this is the standard convention https://mochajs.org/#the-test-directory

**Comment by mhanberg** [comment]
hmm, weird that I can't get it to work. 

I also just checked and when i run `echo expand('%') =~ '\vtests?/.*\.(js|coffee)$'` it returns a one, so it should recognize it as a test file. 

Thanks for the help.

**Comment by codeinabox** [comment]
Does your package.json contain mocha as a dependency? ie

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "mocha": "^3.3.0"
  }
}
```

**Comment by mhanberg** [comment]
I do not because it is bundled in a different library I am using, but I have set the test run explicitly. (On mobile currently, can’t paste the exact line)

**Comment by janko-m** [comment]
@mhanberg @codeinabox Doesn't `package.json` have a lock file now which we can read instead? That way we should be able to catch nested dependencies like these.

**Comment by codeinabox** [comment]
@janko-m it does indeed, though that perhaps should be a fall back as some projects don't use it

**Comment by mhanberg** [comment]
@janko-m yes, and there is also yarn.lock of you use yarn instead of npm.

However my project has no lock file.

**Comment by codeinabox** [comment]
No lock file at all or there exists one but it is ignored by version control?

**Comment by mhanberg** [comment]
No lock file at all.

**Comment by mhanberg** [comment]
I probably should have said this initially, but I am experiencing this issue using vim inside the Windows Subsystem for Linux with Ubuntu. I have had success with the plugin with elixir on my macbook.  Going to update the issue with this information.

**Comment by codeinabox** [comment]
I am curious, why is there no lock file?

As much as we like this plug-in to automatically determine the runner and use a zero configuration approach, this might be best addressed by #185 which lets you override the test runner.

**Comment by mhanberg** [comment]
No lock file due to relying on older node/npm version,  not using yarn, and using a self-rolled boilerplate tool that has some out of date dependencies. These may or may not be addressed in time, but we're sort of at the starting point of the what the boilerplate provides.

> this might be best addressed by #185 which lets you override the test runner.

Are you implying that I should be able to set the test runner now or when that issue gets addressed/closed?

**Comment by codeinabox** [comment]
That is correct though a short term solution would be explicitly add Mocha as a dependency to your package.json instead of being a child dependency

**Comment by mhanberg** [comment]
Okay, thank you!

**Comment by mhanberg** [comment]
Just had the thought, would it be feasible (either right now, or to add to the plugin) to set an alias for a test runner? Meaning I could set it to look for the library that includes mocha instead of mocha itself?.

**Comment by codeinabox** [comment]
This would add a bit more complexity to the plug-in and the detection. I'd rather people add the test framework to their dev dependencies as that's more explicit as it's possible the framework may change their test framework of choice.

**Comment by mhanberg** [comment]
Reasonable, thanks again!

**Comment by Koshila-cd** [comment]
Can I know how to 
"collectCoverageFrom": [
    "**../server.js**"
]
 in the relevant pattern?
