### ISSUE TITLE
csharp.vim Windows, Unable to find .csproj file

### ISSUE THREAD

**Issue by jmzagorski** [janko-m/vim-test#273]
Hello and thanks for a great library.

When running any of the `Test*` commands on Windows 10 I receive the error "Unable to find .csproj file". From what I can debug in https://github.com/janko-m/vim-test/blob/master/autoload/test/csharp.vim, the script assumes the path has `/` instead of `\` as is in windows. When i change all `/` to `\` and remove the `/.` from `let l:filepath = '/'.join(l:filepath_parts[0:-2], '/')` to make it `let l:filepath = join(l:filepath_parts[0:-2], '/')`, my tests run. 

Not sure if there is a config option in vim so vim auto changes it when running based on OS. I can add a check for `has('win32')` or `has('win64')`, but I am not sure that is the best way to do this sort of thing since I have little experience with it.

Its seems this code was first added by @markwoodhall in  https://github.com/janko-m/vim-test/blob/master/autoload/test/csharp/dotnettest.vim  and then moved to https://github.com/janko-m/vim-test/blob/master/autoload/test/csharp.vim by  @aignas (sorry if i am mistaken)

**Comment by janko-m** [comment]
Yeah, we will probably need to conditionally use `\` or `/`, depending on the operating system. From some other plugin I dug up this conditional which I use in strategies:

```vim
has('win32') && fnamemodify(&shell, ':t') ==? 'cmd.exe'
```

If you could send a PR which fixes these slashes for Windows, that would be much appreciated! 😃

**Comment by jmzagorski** [comment]
I will do that. it might take a bit longer since I am not familiar with or have ruby/vim-flavor to create new tests for the forward/backward slash logic.

**Comment by jmzagorski** [comment]
Is there a way to fake/mock the value returned from `&shell`, `has(win32)`, `has(win64`) in these unit tests? Even if I could fake the return value I thought this might be challenging because the shell running the tests would not understand either the forward or backward slash depending on what shell you were testing in. I was able to test using the windows command prompt (through cmder, but that shouldn't matter) and bash through WSL to make sure TestFile, TastLast, TestVisit, TestSuite and TestNearest worked and ran `vim-flavor test spec/` through WSL with no errors.

I have the commit sitting in my repo https://github.com/jmzagorski/vim-test and wanted to wait to hear your opinion on the unit tests for this change.

**Comment by janko-m** [comment]
@jmzagorski I'm not sure how you could do that, only if the wrapper function was a global function, but I would prefer if it's script-local (prepended with `s:`). As far as I'm concerned I think it's ok if we don't test the Windows branches, and rely on manual testing instead.

**Comment by jmzagorski** [comment]
I don't mean to go outside the scope of this issue, but I wonder if there is a better way to handle this slash problem for windows. I notice this is also a problem in the https://github.com/janko-m/vim-test/blob/master/autoload/test/javascript/karma.vim. I have not looked in any other files yet.

**Comment by jmzagorski** [comment]
would you be opposed to having the slash logic populate a global variable in https://github.com/janko-m/vim-test/blob/master/spec/support/helpers.vim that all tests have access to? Something like `test#shell_slash`?
