### ISSUE TITLE
Defining your own custom strategies

### ISSUE THREAD

**Issue by janko-m** [janko-m/vim-test#28]
From @rschmukler:

> @janko-m how would someone create a custom strategy for vim-test? Specifically, when using something like Vundle which uses version control to manage plugins (so you don't want to edit the strategies.vim file)? How do we create a custom strategy given that it appears to be using test#strategy#\<name\> namespacing?

**Comment by jalcine** [comment]
This is an compelling idea. I'd like to see if I could rig my CMake plugin to test compatible projects.

**Comment by janko-m** [comment]
Solved by #51.
