### ISSUE TITLE
Feature request: Vim8/MacVim terminal support

### ISSUE THREAD

**Issue by venables** [janko-m/vim-test#282]
One of my favorite vim-test strategies is the neovim terminal.  Vim8/MacVim offers a similar function to Neovim's `termopen`, called `term_start` , which would be fantastic to use.

Based on the [fzf.vim change for this](https://github.com/junegunn/fzf.vim/issues/416), I've hacked a partially-functioning version of this together myself by modifying the neovim strategy:

```
function! test#strategy#vimterm(cmd) abort
  call term_start(a:cmd)
  au BufDelete <buffer> wincmd p " switch back to last window
  startinsert
endfunction
```

This partially works, though the `tern_start` command does not work properly if you assign env-vars as part of your executable, like `NODE_ENV=test mocha`.

**Comment by janko-m** [comment]
@venables Looks great! Would you mind sending a PR with this strategy?
