### ISSUE TITLE
Name of class incorrect when doing a TestNearest in python, contains inheritance info

### ISSUE THREAD

**Issue by yannack** [janko-m/vim-test#29]
I am trying to run TestNearest on a python nosetest. Here is the command which is being transferred to the neighbor tmux pane:
```
nosetests --doctest-tests test/scanner_manager/test_ballot_processor.py:TestBallotProcessor\(unittest\.TestCase\).test_unmatch_db_ballot_2
```
As you can see, it is considering the class declaration as a subclass of unittest.TestCase to be part of the name of the class, which is incorrect.
TestBallotProcessor\\(unittest\\.TestCase\\) --> TestBallotProcessor

**Comment by janko-m** [comment]
Thanks for reporting. Could you check if this fix works?

**Comment by yannack** [comment]
Seems good to me !
