### ISSUE TITLE
Is is possible to use `:make!` instead of just `make`?

### ISSUE THREAD

**Issue by BlakeWilliams** [janko-m/vim-test#292]
I recently switched to using the make strategy but I'm not a fan of jumping to the first error like `make` does by default without a `!`.

Is it possible to configure the strategy to use `:make!` instead of `:make`? Happy to open a pull request if that's not the case.

**Comment by janko-m** [comment]
@BlakeWilliams Sure, this would just have to be a separate strategy. Notice that for `:Dispatch` and `:Dispatch!` we also have separate `dispatch` and `dispatch_background` strategies.

I'm not sure what would be the appropriate name for the `:make!` strategy, I'll let you choose that 😃

**Comment by BlakeWilliams** [comment]
Thanks!

Just opened https://github.com/janko-m/vim-test/pull/293. Not 100% sold on the name but it's the best I could come up with.

**Comment by janko-m** [comment]
https://github.com/janko-m/vim-test/pull/293 has been merged.
