### ISSUE TITLE
Projectionist test commands

### ISSUE THREAD

**Issue by juanibiapina** [janko-m/vim-test#297]
I use different runner commands for different ruby projects, but they don't match the algorithm that vim-test uses. I currently have my own customized runner that uses projectionist to determine the test command.

Do you think an integration like this would make sense? It would require the runners to be pluggable.

**Comment by kieran-bamforth** [comment]
Is it possible for you to share this customised runner? I am looking at doing something similar and think it is a valid use case.

**Comment by juanibiapina** [comment]
https://github.com/juanibiapina/vim-runner
