### ISSUE TITLE
Quickfix does not parse rspec error when the error message includes [Screenshot]

### ISSUE THREAD

**Issue by measoutdam** [janko-m/vim-test#298]
I'm running rspec test with `'dispatch'` strategy, and expected **quickfix** to render list of _file_name:line_numer_ format for all failed example.
My problem is : Not all failed example will be listed as navigatable in **quickfix**.
And as far as i can tell, the trouble happended only to the failed example with `[Screenshot]` content. Is there a way that we can parse the error message which includes screenshot?

Please refer to below reference.
Thanks in advance.

#### vimrc
```
let test#strategy = "dispatch"
```

#### spec.rb
```ruby
  describe "vim test dispatch" do
    context "when working with example test" do
      it "should equals", :js do
        expect(2).to eq(1)
      end
      it{ expect(2).to eq(1) }
      it{ expect(2).to eq(1) }
    end
  end
```

#### result

there are 3 `it` block, one of which renders error with [Screenshot],

**Quickfix**

[screen quickfix](https://cl.ly/3Q09382A300l)

**Basic**

[screen for basic](https://cl.ly/322F0X1n0o19)

**Comment by janko-m** [comment]
Test.vim doesn't maintain the Vim compiler for RSpec, you should open a ticket a [vim-ruby](https://github.com/vim-ruby/vim-ruby) (but first make sure you're using the latest version of vim-ruby).
