### ISSUE TITLE
Use custom compiler/makeprg in dispatch strategy

### ISSUE THREAD

**Issue by yannack** [janko-m/vim-test#30]
Hello,
I am really liking vim-test, nice job ! However, I have my own compiler for nosetest (which I prefer to the default pyunit one). When I do the following:
```
:compiler mynosecompiler
:set makeprg=nosetests
:make
```
I get a nice output, which I can use to go from error to error with :cnext
But if I do
```
:let test#strategy = 'dispatch'
:TestFile
```
I see it is not using my compiler anymore (nor is it using my makeprg in fact). 
I am not sure how this problem should be addressed, but it would be nice though.

Also, in the same vain, after populating the results in the quickfix, would it be possible to have a hook to run custom vim commands ? I have a nice piece of vimscript which folds the output of nosetests (one fold by test) and makes a nice foldtext, I would love to be able to hook that in.

**Comment by janko-m** [comment]
Try setting in your `.vimrc`

```vim
" :help g:dispatch_compilers
let g:dispatch_compilers = {'nosetests': 'mynosecompiler'}
```

The quickfix list has file type `qf`, so you can write a custom autocommand for when the quickfix gets opened in general:

```vim
autocmd FileType qf call MyNoseFunction()
```

I use this autocommand for making the quickfix list soft wrapped with `setlocal wrap` (because my error output gets really long :P).

**Comment by yannack** [comment]
Right, setting the dispatch_compiler works ! of course, my bad ! Thanks :)
As for the autocmd, that seems very nice :) Any idea how I could run that only for quickfixes which were generated from a test-vim run, but not, say, from a search result ?

**Comment by janko-m** [comment]
Digging through Dispatch's source code, I found something that could work:

```vim
autocmd QuickFixCmdPost make call MyNoseFunction()
```

I don't know if at that point the quickfix is opened, let's hope it is :). If you want only on `:Dispatch`, and not for general `:make`, you can put "dispatch-make" instead of "make".

**Comment by yannack** [comment]
Unfortunately, this does not seem to work, I don't really know why... :(

**Comment by janko-m** [comment]
In what way doesn't it work? Does it not get triggered? Or does it not open the quickfix list? Here is an example of usage from Vim's docs:

```vim
function QfMakeConv()
   let qflist = getqflist()
   for i in qflist
      let i.text = iconv(i.text, "cp936", "utf-8")
   endfor
   call setqflist(qflist)
endfunction

autocmd QuickfixCmdPost make call QfMakeConv()
```

Maybe that means that you have to set the quickfix list manually. Is it how you implemented your folding? I don't think that you can just use normal buffer folding for the quickfix list. It should be your compiler's task to do proper folding, with `CompilerSet errorformat=<your format>`. This is what I can't help you with, because I never played with it, but see `:help errorformat`.

Alternatively you could use the `autocmd FileType qf` and try to get the quickfix "name" (at the bottom, which Dispatch sets to the command that you ran, you could just check if it matches "nosetests").

I hope I gave you enough to chew on, try to see what works best for you. I will close this, since it's not anything related to test.vim in specific.

**Comment by yannack** [comment]
You are right to close it, we might be a little off topic now :)

So, just for sake of completeness, some info:
- `autocmd FileType qf call MyNoseFunction()` works fine, but applies to all quickfix windows (search, tests, etc). So some filtering should be done. At the time of FileType creation, the quickfix_title is apparently not set yet, so I get an error if I try to use w:quickfix_title in the FileType AutoCmd...
- `autocmd QuickFixCmdPost make call MyNoseFunction()` might be working, but not triggered in any of the buffers of interest (quickfix or code)
- `autocmd QuickFixCmdPost cget call MyNoseFunction()` is triggered at the right time, but inside the main python buffer, so the folding is not done on the right buffer

The compiler is not in charge of folding, actually, just of parsing the output of the command and identifying file names, line numbers, messages, and so on. Folding inside the quickfix works as in any other buffer. If I do `call MyNoseFunction()` inside the quickfix it works just fine actually.... My folding actually packs all output relating to a given error inside a single fold (so all locations given by the traceback in python are grouped). 

So for now I am stuck, but I will continue investigating.
