### ISSUE TITLE
TestNearest and projectionist

### ISSUE THREAD

**Issue by ColinRyan** [janko-m/vim-test#303]
Hey, first off, great job with this plugin! I'm loving it!

I'm noticing with projectionist that if I run TestNearest in the class, rather than the test file, it runs all the tests instead of one. How easy would it be to make it run just the one tests? (assuming the names of the test and function only differ by the prefix 'test' )?

**Comment by codeinabox** [comment]
AFAIK whilst we recognise test methods, classes and namespaces there is no such for standard classes so I don't know how we would marry up a class method with its equivalent test

**Comment by ColinRyan** [comment]
So you're saying that a naming convention for methods between a class and it's test in a test file hasn't been standardized?

Is there a documented way for me to make TestNearest decide what to do based on my own custom logic?

Right now the functions I'm testing have a name like 'someName' and the corresponding test would be 'testsomeName'. I'm using phpunit. If I could get the name of the method and prefix it with test I could pass that into phpunits filter param and be on my way :)

**Comment by ColinRyan** [comment]
mmm good idea! Thanks! :)
