### ISSUE TITLE
README.md problem with autocommand

### ISSUE THREAD

**Issue by will133** [janko-m/vim-test#305]
In the README.md, when you mentioned that you can use an augroup to test automatically on write, it's written that you can do:

```
augroup test
  autocmd!
  autocmd BufWrite * if test#exists() |
    \   TestFile
    \ endif
augroup END
```
I got an error with this, however.  Perhaps it should be this?

```
augroup test
  autocmd!
  autocmd BufWrite * if test#exists() |
    \   TestFile |
    \ endif
augroup END
```

**Comment by janko-m** [comment]
Yes, that's right, thanks for letting us know. I'll correct it.
