### ISSUE TITLE
The ability to configuring the Neovim terminal position

### ISSUE THREAD

**Issue by npupko** [janko-m/vim-test#318]
At the moment the position of the new neovim terminal window is hardcoded as `botright new`
[source code](https://github.com/janko-m/vim-test/blob/062c489781c995f7e81103fec8a3c07bd2ff1f4b/autoload/test/strategy.vim#L52).

It would be simply delightful to choose the position of the terminal. For example, run full screen in a new tab, in the active window, or from the top of the active window.
Personally, it would be more convenient for me to run tests in the same window where the file is, and then just go back to it.

I see it like simple configurable `let`
```vimscript
let test#neovim#term_position = "botright"
let test#neovim#term_position = "botleft"
let test#neovim#term_position = "belowright" 
" . . . belowleft, tab, etc.
```

**Comment by npupko** [comment]
I decided to try to complete it. This is my first commit to an open source, so please excuse me if I'm doing something wrong.
I have a few questions about it:
1. I don't really know how i can test it. Can anyone give me a hint?
2. Should we limit the list of user options (botright, botleft)?

**Comment by janko-m** [comment]
> This is my first commit to an open source

Congratulations, that's a big step! 😃 👍 

> I don't really know how i can test it. Can anyone give me a hint?

You don't need to test it, as I chose not to have automated tests for strategies; feel free to just test them manually.

> Should we limit the list of user options (botright, botleft)?

I don't think it's necessary. I think we can just call `:exec` on whatever the user specified, so if they enter a position which doesn't exist, vim will just complain that it's an invalid command.
