### ISSUE TITLE
How to scroll through test results

### ISSUE THREAD

**Issue by luongvo209** [janko-m/vim-test#323]
Right now what I am seeing is when you run a test, a small windows with the position `belowright` is opening in neovim. However, after it ran the tests, you cannot scroll or move with vim key bindings in that window to view all the failed tests, for instance. After a key is press the window disappears right away and takes us back to Neovim

**Comment by janko-m** [comment]
Hello, this is addressed in the README:

> On Neovim the "basic" and "neovim" strategies will run test commands using Neovim's terminal, and leave you in insert mode, so that you can just press "Enter" to close the terminal session and go back to editing. If you want to scroll through the test command output, you'll have to first switch to normal mode. The built-in mapping for exiting terminal insert mode is `CTRL-\ CTRL-n`, which is difficult to press, so I recommend mapping it to `CTRL-o`:
> 
> ```vim
> if has('nvim')
>   tmap <C-o> <C-\><C-n>
> endif
> ```

**Comment by luongvo209** [comment]
Thank you so much @janko-m . Sorry for missing that part.
