### ISSUE TITLE
Document how to run the testcases

### ISSUE THREAD

**Issue by nixon** [janko-m/vim-test#33]
It would be nice to be able to run the testcases prior to submitting pull requests, but I don't see any documentation on how to do that.  I'm guessing it involves `rspec`, but not being a ruby guy, I'm not sure what to do.

**Comment by janko-m** [comment]
Yeah, it's a bit unhappy that you have to run Vim tests with a Ruby test runner. I wanted to use `Vader.vim` test runner, which is in pure VimScript, but I couldn't use it for these kind of tests. Hopefully it's easy to run the tests once you have Ruby installed.

Thanks for reporting this lack of documentation :)

**Comment by nixon** [comment]
I'm on OS X (Yosemite) and had to use `sudo gem install vim-flavor`, and then had to go and update permissions so that non-root could read the files:

```
find /Library/Ruby/Gems/2.0.0/gems/vim-flavor-2.2.1/ -type f -print0 | xargs -0 chmod og+r
find /Library/Ruby/Gems/2.0.0/gems/vim-flavor-2.2.1/ -type d -print0 | xargs -0 chmod og+rx
```

I also had to `sudo gem install bundler`.  At this point, the testcases ran but I had several failures:

```
Test Summary Report
-------------------
spec/mocha_spec.vim        (Wstat: 0 Tests: 7 Failed: 6)
  Failed tests:  1-4, 6-7
```

I tried `sudo gem install mocha` but the same tests still failed.  Tried installing some node.js things:

```
brew update
brew install node
npm install -g mocha
npm install -g coffee-script
```

but then get the following error:

```
# -----------------------------------------------------------------------------
# {vspec}..<SNR>2_run_suites..8..11..Teardown, line 1
# Vim(bufdo):E325: ATTENTION
Bailout called.  Further testing stopped:  Unexpected error happened while processing a test script.
FAILED--Further testing stopped: Unexpected error happened while processing a test script.
```

which I think is related to the coffeescript test:

```
mocha (master) $ pwd
~/.vim/bundle/vim-test/spec/fixtures/mocha
mocha (master) $ mocha test/normal.coffee

~/.vim/bundle/vim-test/spec/fixtures/mocha/test/normal.coffee:1
nction (exports, require, module, __filename, __dirname) { describe 'Math', ->
                                                                    ^^^^^^
SyntaxError: Unexpected string
```

I'm not sure where to go from here...

**Comment by janko-m** [comment]
Why did you `sudo gem install vim-flavor`, shouldn't it be possible without `sudo`? You should need to install `bundler`. In case you're not succeeding with system Ruby, try rbenv:

```sh
$ brew install rbenv ruby-build
$ eval "$(rbenv init -)" # you can later put it in your ~/.bash_profile
$ rbenv install 2.2.1 # this will take a while (< 10 minutes)
$ rbenv global 2.2.1
$ gem install vim-flavor
$ vim-flavor test spec/
```
You don't need to install node, mocha or coffeescript, the tests are run in isolation, no actual commands are being run (the tests are just checking which commands are being generated).

**Comment by nixon** [comment]
Thanks!  That worked.
