### ISSUE TITLE
Is there any way to execute a single dataprovider as "nearest" test within PHPUnit?

### ISSUE THREAD

**Issue by DanielSiepmann** [janko-m/vim-test#333]
In PHPUnit one test (a method) can have a DataProvider (another method).
This method returns an array of possible data to run the test.

It would be awesome if it's possible to put the cursor inside a single data and run this as "nearest".

The PHPUnit call might look like: ` ./vendor/bin/phpunit --filter "Swap columns, from large to large"`

While PHPCode might look like:
```
    /**
     * @test
     * @dataProvider getPossibleCombinations
     */
    public function renderedTemplateReturnsExpectedPHPCodeForProvidedData(
        array $data,
        string $expectedOutput
    ) {
        // test code
    }

    public function getPossibleCombinations(): array
    {
        return [
            'Swap columns, from large to large' => [
                'data' => $this->getRecordData(),
                'expectedOutput' => "Hello World",
            ],
        ];
    }
```

I know this might not be an easy one.

**Comment by codeinabox** [comment]
Are you able to filter manually using the CLI? There seems to be options the [--filter option](https://phpunit.de/manual/6.5/en/textui.html) seems to allow you to add a data set. If you can create an example of the test and the expected CLI call we could try adding this feature.

**Comment by janko-m** [comment]
This kind of advanced language-specific parsing is out of scope for vim-test, as vim-test would now have to know how to parse PHP code, as this is not parsing out function names anymore, here it'd have to get something out of the function *body*.

**Comment by DanielSiepmann** [comment]
@codeinabox I've added exactly this in my request ;) The PHPUnit call includes the filter option and the Code beneath displays the matching Source Code.

But I understand that this is out of scope @janko-m. Just hoped it might still get implemented or there is a hint how to add this myself. Would be a huge time saver in one of our projects.

Thanks anyway, and thanks for this awesome plugin.
