### ISSUE TITLE
Remove 'rails' from zeus command

### ISSUE THREAD

**Issue by ahoglund** [janko-m/vim-test#336]
👋 Hey.

I am tryin to run `vim-test` with zeus on a Rails 5.2, Minitest 5.11.3 app.  I noticed that the out-of-box functionality is to run `zeus rails test ` + file(s) if the `.zeus.sock` file is detected. [code](https://github.com/janko-m/vim-test/blob/062c489781c995f7e81103fec8a3c07bd2ff1f4b/autoload/test/ruby/rails.vim#L29)

From my reading of the zeus [documentation](https://github.com/burke/zeus), it seems the `rails` command is superfluous.  Instead, it should just run `zeus test` + file(s).

I'd be happy to submit a PR to change/fix this, but wanted to open this to ensure there wasn't a way to overcome this with a configuration setting.

Thanks!

**Comment by janko-m** [comment]
You can set g:test#ruby#minitest#executable variable to `zeus test`. But if that’s the way to run zeus test commands, it should probably be updated in vim-test.

**Comment by ahoglund** [comment]
Alright, I'll do that for now then. Thanks for the quick response!

**Comment by ahoglund** [comment]
I had to instead to modify: 

```
test#ruby#rails#executable = 'zeus test'
```

to get this working.

**Comment by janko-m** [comment]
Good catch, forgot that there is a special `rails` test runner in vim-test. Btw, I pushed the change from `zeus rails test` to `zeus test` to master.
