### ISSUE TITLE
error when running Go tests

### ISSUE THREAD

**Issue by kevinburke** [janko-m/vim-test#34]
Not sure quite what's going on - this is a smaller example than my actual test, which doesn't compile, but is sufficient to reproduce the issue. in this test file:

```
func TestSwap(t *testing.T) {
	a := &Member{
		Track: []tracks.Element{
			{Segment: tracks.TS_MAP[tracks.ELEM_FLAT]},
			{Segment: tracks.TS_MAP[tracks.ELEM_25_DEG_UP]},
		},
	}
	if a.Track[0] != "" || a.Track[1] != "" {
		t.Errorf("expected d to be %v, was %v", dexpected, d.Track)
	}
}
```

If I call `:TestNearest` from the `a :=` line, the test runs fine. If I call it from the `if` statement, I get the following error:

```
Error detected while processing function WriteAndRunTest..test#run..test#base#build_position..test#go#gotest#build_position..<SNR>94_nearest_test..test#base#nearest_test:
line   18:
E684: list index out of range: 0
E116: Invalid arguments for function add 
```

Not sure what's going on, I haven't dug into the guts of the plugin. Let me know if you need more data about my system. I'm running vim-test commit 5ca90c0.

**Comment by janko-m** [comment]
Thanks, that's all I need to start digging. The error happens when parsing the file for running the nearest test, I just need to correct that function.
