### ISSUE TITLE
Could not find command

### ISSUE THREAD

**Issue by StevenXL** [janko-m/vim-test#340]
Hi Everyone,

I am having an issue running my `RSpec` tests in a Rails project.

I have two projects - project `A` works fine when I use the command `:TestFile`.

Project `B` does not work. When I run `:TestFile`, I get an error such as `Could not find command "spec/models/user_spec.rb".`.

Because running specs works in one project and not another, the issue is obviously with my setup, but I don't have any idea where to start looking in order to solve the issue.

Any help would be appreciated. Thank you.

**Comment by janko-m** [comment]
What is the command that vim-test runs? You can see it printed out if you use Vim (not Neovim) with the default strategy.

**Comment by StevenXL** [comment]
Hello @janko-m. Thank you for taking the time to reply. 

When I run `:TestFile` in **vim**, I get the following output:

```
./bin/rspec spec/models/user_spec.rb
Could not find command "spec/models/user_spec.rb".
```

When I run `rspec` from the shell, I have to run `bundle exec rspec spec/models/user_spec.rb`. This definitely gives me some areas to explore. I'll write back if I can figure out how to get this to work.

**Comment by StevenXL** [comment]
OK - it seems like installing `rspec` into my gemset did the trick. `gem install rspec`. Thank you!
