### ISSUE TITLE
mocha: support react JSX files

### ISSUE THREAD

**Issue by mpareja** [janko-m/vim-test#43]
The implementation should be similar to that of the mocha coffee script integration.

**Comment by janko-m** [comment]
What options should I pass to Mocha if I detect JSX files?

**Comment by mpareja** [comment]
Whoops, went on vacation and unplugged - sorry for the delay in responding. Sounds like you've sorted this out: you're a :star2:!

**Comment by janko-m** [comment]
I [removed](https://github.com/janko-m/vim-test/commit/6555be646dd4d1615c7ff16179b8ff82b12490a4) the compiler support for JSX, because I realized it's a better convention to set the compiler options in test/mocha.opts (I wanted to be consistent with removing the CoffeeScript compiler option).

**Comment by mpareja** [comment]
:+1: I was surprised you supported compilers and could see this becoming a support nightmare for you :D.
