### ISSUE TITLE
Possible to add Behat support which uses Cucumber feature files?

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#45]
I'd like to add [Behat](http://docs.behat.org/) support but is it possible if it also uses Cucumber feature files like the Ruby Cucumber runner or would they conflict?

**Comment by janko-m** [comment]
That's a good question. At first I was thinking that Cucumber won't proceed unless you create a `features/support/env.(rb|java|php|...)` file, which it uses to detect the language. But I think this now changed to which runner you installed on your system (`gem install cucumber` means Ruby, `pip install cucumber` means Python).

I think a good solution would be to add to the existing Cucumber runner a check that there are no *.php files in the features/ directory (and if there are, then it Cucumber's `test_file()` returns false). Would that be feasible?

**Comment by codeinabox** [comment]
Yes that makes sense or you could check for the presence of [behat.yml](https://behat.readthedocs.org/en/v2.5/guides/7.config.html) perhaps

**Comment by janko-m** [comment]
Does this file always have to be present? Cucumber also has a `cucumber.yml`, but it's optional and I often don't create it.

**Comment by codeinabox** [comment]
It may be optional, checking for the presence of PHP files is probably the safer option
