### ISSUE TITLE
PHPUnit and Behat configuration in subdirectories

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#49]
I've tested the PHPUnit and Behat runners and it works great except for when the configuration is in a subdirectory. How can I code `#build_args` to look for a phpunit.xml or behat.yml recursively?

**Comment by janko-m** [comment]
You want to extract something out of `phpunit.xml` and `behat.yml`? I think the best way would be

```vim
glob('**/phpunit.xml')[0]
glob('**/behat.yml')[0]
```

These will throw an error if the glob is empty, so you may want to add an `if !empty(glob(...))`, or you can use `get(glob(...), 0)`, which will return "0" when the index is missing (that is, when the glob is empty).

**Comment by codeinabox** [comment]
Don't want to extract anything, just want to properly set the configuration path if it's not in the root directory eg

> phpunit -c site/tests/phpunit.xml

I create a patch and try using hub to turn this issue into a pull request

**Comment by janko-m** [comment]
Just a friendly reminder if you maybe have time to take a stab at this :)

**Comment by codeinabox** [comment]
Still on my radar. One thing that I need to consider in my approach is to not look for phpuinit.xml in vendor directories

**Comment by codeinabox** [comment]
Managed to make some headway on this but got two problems to solve. Firstly, how do I exclude things from the glob pattern. At the moment it returns all the below results but all I want is `site/test/phpunit.xml`

> site/test/phpunit.xml
site/vendor/aura/sql/tests/phpunit.xml
site/vendor/jalet/tvnu-config/phpunit.xml
site/vendor/mockery/mockery/examples/starship/phpunit.xml
site/vendor/mockery/mockery/tests/phpunit.xml

Secondly how do I make build args appear before the test file? ie `phpunit -c tests/phpunit.xml tests/NormalTest.php`

**Comment by janko-m** [comment]
1. It doesn't seem that Vim's `glob()` has a negative pattern match. Maybe you could solve this by matching the normal glob and subtracting the `vendor/` glob (subtracting two arrays as sets, I don't know what's the function for that though).

2. You just need to define the `build_args()` function in the following way, that you prepend to the options array:
  ```rb
  function! test#php#phpunit#build_args(args) abort
    return ['-c test/phpunit.xml'] + a:args
  endfunction
  ```

**Comment by janko-m** [comment]
Sorry for poking again, this is the only open issue :). Did you manage to get somewhere with this?

**Comment by codeinabox** [comment]
I did, will try to finish it off or post what I've done



—

**Comment by janko-m** [comment]
I will close this for now, because I don't know how to solve this myself without PHP knowledge, someone will make a PR eventually if it turns out to be an issue.
