### ISSUE TITLE
Detect Testing Support for Ember

### ISSUE THREAD

**Issue by jalcine** [janko-m/vim-test#50]
[Ember](http://emberjs.com/) has a [convenience test runner](http://guides.emberjs.com/v1.13.0/testing/#toc_how-to-run-your-tests) via [QUnit](http://qunitjs.com/). This issue is more of a placeholder (and feedback generator) to see if having support for this in vim-test would be nice.

Indirectly related to #28 - if that issue's implemented, this could be provided via an alternative snippet.

**Comment by janko-m** [comment]
I think it would definitely be nice to have this. Maybe we could call the test runner "Ember", or create a "QUnit" runner which has conditionals for Ember. How do you detect an Ember project? Is there some file which vim-test can detect, which is specific to Ember projects?

**Comment by jalcine** [comment]
Fortunately, yes. Most modern Ember projects have a lingering `.ember-cli` file in their tree; though for the most accurate detection would be scanning `package.json` at the route and determining the core Ember package is being used. From there, it's up to the user to have it installed (we can't do everything! :grinning:) for it to be run. Running a test for Vim is as simple as `ember test`.

**Comment by janko-m** [comment]
Ok, I think I'll check for both, just in case someone isn't using a package that depends on Ember, in which case they wouldn't have it listed in `package.json`. Small chance, I know, but just in case.

Does Ember have a naming convention for test files? For example, in Ruby we end our files with "_test.rb" or "_spec.rb". Test files are always located in the `test/` directory, right?

**Comment by jalcine** [comment]
Yes, by convention, tests for Ember are placed under the `test/` directory. Ember's very much like Rails when it comes to some conventions.

**Comment by jalcine** [comment]
Tbf, I have no problem implementing this myself but I'd rather work on/wait for #28 because that'd make it a _lot_ more interesting in terms of implementing strategies.

**Comment by janko-m** [comment]
Test frameworks in test.vim usually produce a shell command as a result, and strategies are just a way for how those shell commands will be run. I don't think it would have an effect in how you write the Ember runner, so I don't think you have to wait.

**Comment by jalcine** [comment]
@janko-m Awesome! Weekend's coming up so I think I'll look into this then (either a PR or maybe a Wiki page / blog post on how to incorporate it :dart:).

**Comment by janko-m** [comment]
PR would be great, because it's a feature that test.vim should definitely have. Or if you don't have time, I can go implement it with the help of your Ember knowledge.

**Comment by janko-m** [comment]
@jalcine If you have time to work on this, that would be great. I'm closing this issue, since it's a feature request which I'm not ready to implement myself. This is mainly because `ember test` seems to not support the most basic features like running all tests in a single file.

**Comment by jalcine** [comment]
Understood. I’ve been a bit busy as well but I’ll keep looking into this.

On Tuesday, September 15, 2015 12:56:17 PM Janko Marohnić wrote:
> @jalcine If you have time to work on this, that would be great. I'm closing
> this issue, since it's a feature request which I'm not ready to implement
> myself. This is mainly because `ember test` seems to not support the most
> basic features like running all tests in a single file.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/janko-m/vim-test/issues/50#issuecomment-140518732


Jacky Alciné[1] // Work[2] // Blog[3] 
Software Engineer
---

They can READ + SEE everything in this email. In your texts.
The NSA's been spying on US citizens for too long.
Read more: https://www.eff.org/nsa-spying

--------
[1] https://jacky.wtf/?ref=email
[2] https://jacky.wtf/work/?ref=email
[3] https://jacky.wtf/weblog/?ref=email

**Comment by thiagofelix** [comment]
In case anyone still looking for some like this I've done one limited integration that you can reuse or build upon:
https://gist.github.com/thiagofelix/8b7f1df9c9bb066d97fa6324d4edf9c2
