### ISSUE TITLE
Running tests remotely eg Vagrant VM or SSH

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#53]
I am trying to work the best way to run tests remotely, particularly in the case of running them inside in a Vagrant VM. Is there an existing plug-in that this plug-in could leverage off?

**Comment by janko-m** [comment]
Hmm, I haven't executed tests in this way so far, so I don't know of any plugins, but it would be great to leverage one to do the hard work.

**Comment by codeinabox** [comment]
The [vado plug-in](https://github.com/hamishmack/vado) might be a good candidate

**Comment by jalcine** [comment]
[**@codeinabox**](https://github.com/codeinabox) commented on [Aug 18, 2015, 8:27 AM EDT](https://github.com/janko-m/vim-test/issues/53#issuecomment-132192429 "2015-08-18T12:27:24Z - Replied by Github Comment Enhancer"):
> The [vado plug-in](https://github.com/hamishmack/vado) might be a good candidate, lets you remotely run commands over SSH which is the way [PHPStorm does it too](https://confluence.jetbrains.com/display/PhpStorm/Running+PHPUnit+tests+over+SSH+on+a+remote+server+with+PhpStorm).

That plugin has a hard dependency on using sshfs (which is a bit funky on Macs, iirc). If Vagrant's the target, why not have a means of prefixing commands with `vagrant ssh --` or the likes?

**Comment by janko-m** [comment]
I think there aren't any other Vim vagrant plugins, so I think it would be fine to make a strategy which uses `vagrant ssh` directly. What do you have to do besides `vagrant ssh --command "..."`? Do you have to specify the name of your Vagrant "container" (I forgot how they're called), or does Vagrant figure that out by itself using the Vagrantfile?

**Comment by codeinabox** [comment]
Usually when you run `vagrant ssh` you have to change the working directory to where the code is mounted before running the tests, so potentially a command like this

`vagrant ssh --command "cd /home/vagrant/project; ./vendor/bin/phpunit`

**Comment by janko-m** [comment]
Here, I pushed my implementation of this strategy, let me know how it works for you.

**Comment by janko-m** [comment]
I've [removed](https://github.com/janko-m/vim-test/commit/774f101f3f486392be0618d88475a1bbb598e713) the Vagrant strategy (reasons explained in the commit), but I've [introduced](https://github.com/janko-m/vim-test/commit/5532281a72ab8593a83e4ebc484640ecdb529ab6) a new concept of "transformations" which allows you to add it manually (the example in the README sets up Vagrant).

**Comment by codeinabox** [comment]
Yeap saw that, will have a try. Should be handy when you developing locally but need to run the tests via Docker, Vagrant, ssh

**Comment by codeinabox** [comment]
Would it be possible to define transformations on just a buffer level?

**Comment by janko-m** [comment]
Hmm, I didn't consider it, what would be the use case? Maybe it would make sense to allow different transformations for different runners. Probably would be useful to add that feature to strategies, too.

**Comment by codeinabox** [comment]
I am trying to set up transformations to run only when certain environment variables are set eg VAGRANT_DIR but I guess because I different Vim instance per project global would be fine right?

**Comment by janko-m** [comment]
Hmm, I don't know if it works for you, but in your .vimrc you could do conditionals based on environment variables, so set different tranformations depending on the variable (unless the variable changes dynamically while you're running the Vim session).
