### ISSUE TITLE
Clear escape codes in vim-test output

### ISSUE THREAD

**Issue by kevinburkeshyp** [janko-m/vim-test#59]
When I run `mocha` (mochajs.org) tests with `vim-test` in MacVim, I get `^[[2K^[[0G` appearing at the start of the line. It would be nice if those characters were filtered from the output. 

Here's an example patch for this issue in `vim-dispatch`: https://github.com/tpope/vim-dispatch/pull/86

Here is a screenshot of the issue.

<img src="https://api.monosnap.com/rpc/file/download?id=2qRzsc7RG4VCEKINuIf1Fa5lz0thAt" />

**Comment by janko-m** [comment]
Do you know if both MacVim and GVim don't support Terminal colors when executing `:!`? I thought that instead of parsing escape codes (which I'm not sure how I would do, I'm unfortunately not an expert on UNIX pipes like Tim Pope :stuck_out_tongue:), I could instead just tell each runner not to use colors if we're in GUI (that is, if `has('gui')` is true).

**Comment by kevinburkeshyp** [comment]
> Do you know if both MacVim and GVim don't support Terminal colors when executing :!?

I don't know... see http://stackoverflow.com/a/11676713/329700 which makes it sound like there's little hope. I should just abandon MacVim but having a separate application/window for vim is nice.

**Comment by kevinburkeshyp** [comment]
Thanks for the fix! Testing now.

**Comment by kevinburkeshyp** [comment]
Darn, I am still getting those odd escape sequences in Macvim... I'll check and see if mocha is printing something odd, and see if there's a way to turn it off.

**Comment by kevinburkeshyp** [comment]
(also-  just double checked I am running vim-test commit ade563c4b7b874131041513043a71192857d68a0)

**Comment by janko-m** [comment]
You're using the default `test#strategy`? Is `--no-colors` added to the executed command?

**Comment by janko-m** [comment]
You're right, I'm getting them too. It seems Mocha is adding those even when you turn off colors.

**Comment by janko-m** [comment]
Ok, this are some color-unrelated escape sequences that Mocha creates (even though it shouldn't). I copy-pasted the solution for the vim-dispatch issue, so in MacVim a `sed` command will be appended:

```rb
:!mocha --no-colors spec/fixtures/mocha/test/normal.js | sed -e "s/.*\e\\[2K\e\\[0G//g"
```

The only downside is that you will see this as an executed command. Would that be feasible?

**Comment by janko-m** [comment]
Mocha actually inserts a "carriage return" character (U+000D, or 13 by ASCII), if I pipe the command through empty `sed`, it isn't visible anymore in MacVim, but it's still there (you can see it if you pipe it to less). Anyway, I pushed a fix that removes this character through `sed`.

**Comment by brandoncc** [comment]
Has anyone ever figured out how to do this? I have the same problem with ruby tests and Dispatch.vim.
