### ISSUE TITLE
Is there a way to add some indication that test is running

### ISSUE THREAD

**Issue by firedev** [janko-m/vim-test#60]
This is related to NeoVim apparently, didn't had this issue in Vim because everything is flickering there so you can tell that there is some activity. In NeoVim the screen is rock solid and I am always like – did it ran tests at all?

Is is possible to add some indication that test is running?

**Comment by janko-m** [comment]
Hmm, which strategy are you using? I know that that [Neoterm](https://github.com/kassio/neoterm) has something like this built in, you can see the emoji changing in the GIF, it's probably easy to set up.

**Comment by firedev** [comment]
Hi, I use: `dispatch`. Let me try with neoterm...

**Comment by firedev** [comment]
I use `dispatch` same as I was using in Vim. I like the behaviour because it opens QuickFix window if there are failing tests. `neoterm` and `neovim` keep the terminal window opened while tests are running and in fact making everything even more distracting. 

With `dispatch` it hides terminal completely until there is a failing test result. Just what doctor ordered. If only there was some slight indication that test is running...

**Comment by janko-m** [comment]
Aaaa, you could've said you're using dispatch.vim, I thought it was NeoVim-specific. Dispatch.vim actually fires up "events" in Vim when it starts and when it finishes. You could test it by running

```vim
:au QuickFixCmdPre dispatch-make echoerr "Works!"
"   | -- type --- | -- name --- | -- command --
```

Now when you run a dispatch command, you should get the error message. The two events fired are `dispatch-make` and `dispatch-make-complete`, so you could hook up to them and do whatever you want. It's probably most visible to change the status line, I don't know how this is done but I'm sure you can find out quickly.

**Comment by firedev** [comment]
I see, thanks. However now it says "Works!" but plugin crashes or something:

```
Error detected while processing QuickFixCmdPre Auto commands for "dispatch-make":
Works!
Error detected while processing function test#run_last..test#shell:
line   10:
E171: Missing :endif
Error detected while processing function test#run_last:
line    2:
E171: Missing :endif
Press ENTER or type command to continue
```
