### ISSUE TITLE
Capturing failing tests?

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#67]
One thing I was thinking that would be very handful if it was able to capture the output of failing lists and easily let you open those files with failing tests in the buffer or perhaps as a CtrlP plugin like [ctrlp-modified](https://github.com/jasoncodes/ctrlp-modified.vim)

**Comment by janko-m** [comment]
Doesn't vim-dispatch already have similar functionality?

**Comment by codeinabox** [comment]
Not that can see in the documentation.

**Comment by janko-m** [comment]
I mean, it doesn't save the output to a file, but it makes a quickfix out of test errors, which you can then easily navigate with vim-unimpaired. I think this should be more than suitable for most people.

Any integration like the one you're describing can be implemented by adding a custom strategy, and is not something I think vim-test should ship with.
