### ISSUE TITLE
TestNearest won't work with @test annotation

### ISSUE THREAD

**Issue by mjacobus** [janko-m/vim-test#74]
TestNearest wont work with test annotation:

Vim test won't recognize that functions annotated with "@test" are also test. Therefore when `TestNearest` is run it will behave like `TestFile`.
```php
/**
 * @test
 */
public function foo()
{
    $this->assertTrue(false); # cursor here
}
```

The below code works

```php
public function testFoo()
{
    $this->assertTrue(false);  # cursor here
}
```

If you accept I can try to write a PR. Any tips on how to run the tests?

**Comment by janko-m** [comment]
Hey, thanks for reporting. Yes, I would accept a PR for this. If you have Ruby installed, it's just a `gem install vim-flavor` and you can run `:VSpec` when inside of Vim. Alternatively I could add Travis CI which would run the tests for you.

The only problem is that `test#base#nearest_test()` can currently only find matches on the line where the test name is seen. So, if it sees `@test`, you cannot tell it to go down until the function definition. Maybe the function could be extended somehow, alternatively you could copy that behaviour to the Maven runner and alter it to do what you want.

**Comment by mjacobus** [comment]
Thank you @janko-m! I will give that a try =)
