### ISSUE TITLE
Suggestion to use Travis CI to run specs

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#78]
Using [vim-flavor it is possible run the Vim specs on Travis CI](http://whileimautomaton.net/2013/02/08211255)

**Comment by janko-m** [comment]
Thanks for the suggestion, done in https://github.com/janko-m/vim-test/pull/80.

**Comment by codeinabox** [comment]
Great, you can also add the [build status to the README](https://docs.travis-ci.com/user/status-images/)

**Comment by janko-m** [comment]
Thanks for the suggestion, but I'm kind of against those badges, I don't think they should be part of the README. I already receive build failures by email, so for me that's all I need :)
