### ISSUE TITLE
Pre-requisite on iTerm2 *beta*

### ISSUE THREAD

**Issue by andrewferrier** [janko-m/vim-test#79]
Thanks for your work on vim-test; it's a very helpful tool. I think it would be useful to clarify in the `README.md` that (currently) the iterm strategy depends on a beta level of iTerm2. I was using iTerm 2.1.3; this doesn't work as it fails on the `set _window to (current window)` line in `bin/osx_iterm`. Upgrading to iTerm 2.9.20151111 fixed it; it looks like the AppleScript hooks have changed: https://iterm2.com/applescript.html.

**Comment by janko-m** [comment]
Thanks for letting me know, I didn't realize that it was a beta release, hopefully people are ok with upgrading.

**Comment by andrewferrier** [comment]
Yep, just thought it was worth pointing out to save others needing to figure it out - the standard intern version with Homebrew wouldn't work with vim-test as-is. Thanks for fixing the docs and your hard work on vim-test.
