### ISSUE TITLE
Option for disable runner commands

### ISSUE THREAD

**Issue by chemzqm** [janko-m/vim-test#83]
vim-test is a real helpful plugin for testing, only one thing annoying (at least for me),  it added lots of runner  commands. 

Since the runners commands names differently, they pollute my commands and could possibly lead conflict.  As I can config `:TestNearest ` `:TestFile` to works with different kinds of files,  and I rarely have specific option for the test command, they're useless for me.

My suggestion is add an option to disable all of the runner commands.

**Comment by janko-m** [comment]
Good point. I added them to easily run the test suite when you didn't run any tests yet, but I forgot that polluting the namespace means polluting the command autocompletion. Just to be clear, you want to disable only the `:RSpec`, `:Mocha`, `:PyTest` etc. commands, not the `:TestFile`, `:TestNearest` etc. commands, right? I think it's even better idea to have them disabled by default and bump the major version.

**Comment by chemzqm** [comment]
Sure, that would awesome :+1:

**Comment by codeinabox** [comment]
:+1:

**Comment by janko-m** [comment]
I decided that, instead of having an all-or-nothing boolean variable, it would be better if users can choose the commands they want (so that only they are defined):

```vim
let g:test#runner_commands = ['Minitest', 'Mocha']
```

**Comment by codeinabox** [comment]
Would it be possible to define command on a buffer level?

**Comment by janko-m** [comment]
I was never really a fan of buffer-only commands. It never set quite right for me in vim-fugitive that when I open an empty buffer I don't have any of Fugitive's commands. When using vim-test I would like that all commands are present regardless of which buffer is opened.

**Comment by codeinabox** [comment]
Point taken. I guess I only use about three runner commands at the moment so having them global probably isn't needed.
