### ISSUE TITLE
Add Always Use Absolute Path Option?

### ISSUE THREAD

**Issue by bradurani** [janko-m/vim-test#84]
I've run into an issue with relative paths. We have a Rails project with internal engines and internal gems. To run the specs in the engines and gems you have to cd into the engines directory in the terminal.

That causes a problem the first time you run a spec because the spec doesn't run from the right directory, but it's not a big deal because you can cd in the terminal and rerun and be good for the rest of the day.

There's a bigger problem however in that after you've done that, running the specs from vim-test uses a path relative to the project root. Do you think it's worthwhile adding a config variable to vim-test that will force it to send an absolute path to the terminal for every spec run?

**Comment by janko-m** [comment]
Yes, adding that option makes a lot of sense, I'll add it later today.

**Comment by janko-m** [comment]
I reread your issue description one more time, and I realized that I don't fully understand the problem. Vim-test doesn't create paths relative to the project root, it creates them relative to the working directory. So when you `cd` in and out of the engine, vim-test should always generate correct paths, since it should always be relative to the directory where you `cd`ed.

**Comment by bradurani** [comment]
Ahhh... ok

For my workflow to function, I have to have Vim in the project root and the shell in the engine root. So I have to run the spec once, which errors, go to the shell, cd into the engine, go back to vim and run the spec again. That's when vim-test sends a relative path to the shell that doesn't match up.

**Comment by janko-m** [comment]
Aha, I think I understand now, you're probably using a strategy where you send commands to the other shell window, the one which is `cd`ed into the engine root. Ok, I will add this option the first thing tomorrow.

**Comment by bradurani** [comment]
Thank you so much!!!!
