### ISSUE TITLE
Minitest - missing TEST and TESTOPTS after Neoterm update

### ISSUE THREAD

**Issue by aradunovic** [janko-m/vim-test#86]
I'm having trouble running Minitest tests with `neoterm` strategy after neoterm update.
The output looks like this:

```bash
$ ./bin/rake test TEST=
rake aborted!
LoadError: cannot load such file -- /Users/aleksandar/Projects/some-project
-e:1:in `<main>'
Tasks: TOP => test:single
(See full trace by running task with --trace)
```

As you can see `TEST` does not have any value and `TESTOPTS` is missing. Result is the same whether I'm running single test, single file, last or all tests.

I'm using [vim-plug](https://github.com/junegunn/vim-plug), so I managed to trace down the issue to [8551ed5](https://github.com/kassio/neoterm/commit/8551ed52df2594c36e68dc06b3634f4565c8a3a4). This and all later commits cause the issue above to appear.

**Rspec** tests are running fine.

I'm using **Neovim** and settings concerning `Neoterm` and `vim-test` in my `rc` are:

```vim
let g:neoterm_position = 'horizontal'
let g:neoterm_automap_keys = ',tt'
let g:neoterm_size = 30

let test#strategy = "neoterm"
```

**Comment by janko-m** [comment]
Hmm, strange that this commit introduced the bug, it should only affect the appearance of the "|" character. Thank you for the detailed report, it's probably an escaping issue, I will investigate when I get home.
