### ISSUE TITLE
Make use of Spring

### ISSUE THREAD

**Issue by jvanbaarsen** [janko-m/vim-test#90]
I'm trying out this plugin in combination with Dispatch, but it looks like the tests are not making use of Spring. Do I need to configure something for this?

**Comment by janko-m** [comment]
Test.vim should automatically detect and use Spring-generated binstubs (`bin/rake`, `bin/rspec`, ...), which should be automatically generated with `rails new`. Alternatively they can be generated by running `spring binstub --all`.

**Comment by jvanbaarsen** [comment]
Hm ok, I'm now using the default runner and not Dispatch, in that case it works :)

**Comment by janko-m** [comment]
Test.vim generates the same shell command regardless of which strategy you're using (default or Dispatch). When you use the Dispatch strategy, you can check which shell command was generated by looking at the status bar of the quickfix window that Dispatch generates when there are test errors.

**Comment by jvanbaarsen** [comment]
@janko-m Ok thanks :-) Will take a look
