### ISSUE TITLE
Default Python errorformat does not work with Dispatch handler

### ISSUE THREAD

**Issue by DXist** [janko-m/vim-test#92]
Hi! Thank you for an excellent idea to unify application testing inside Vim!

I use vim-test with tpope/vim-dispatch handler and run tests for a Python app.
I set default `errorformat` string that Vim help suggests for Python tracebacks:

```
setlocal errorformat=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
```

Unfortunately this format doesn't match the output coming from Dispatch.
At the moment traceback is parsed and put to the quickfix list as a single error. I want to have a list of errors - separate error for each traceback item.

I can see `|| ` prefix (two pipes and a space) in each line of quickfix item (at least - in my setup). It could be a reason of failed traceback parsing.

Do you also have this prefix? Thank you in advance!

**Comment by janko-m** [comment]
Yes, the `|| ` prefixes are there for every unparsed line, it's I think added by Dispatch.vim, and certainly not the cause the parsing error.

Unfortunately I cannot really help with composing a `errorformat`, as I don't have any exprience in it. I presume this also doesn't work when you're using Dispatch.vim directly? In that case you can maybe search help in some general Vim forum.

**Comment by DXist** [comment]
Thank you for the response! I guess I need to discuss the issue with @tpope.

**Comment by janko-m** [comment]
While he would definitely be able to help you, I don't think that he has much time for helping with something which is not a bug in Dispatch.vim. The concept of compilers exists in vannila Vim (it's used by `:make`), Dispatch just mounts on that feature. My guess that there is just some mistake in your `errorformat` string.
