### ISSUE TITLE
Vimux Strategy - Unknown Function: VimuxRunCommand

### ISSUE THREAD

**Issue by mikeLspohn** [janko-m/vim-test#94]
While using the `vimux` strategy, I get "Unknown Function: VimuxRunCommand" error.

Here's the setting in my vimrc: 
`let test#strategy = "vimux"`

**Comment by janko-m** [comment]
Did you download and include the Vimux plugin to your vim environment?

**Comment by jtdowney** [comment]
Also, in much older versions of vimux the command names were different. So even if you have vimux, make sure it is the latest version.
